### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by ErenPhayte** [aubio/aubio#108]
Hi,

Just running the python demo and I get segmentation faults

> demo_bpm_extract.py songfile.aac

[aac @ 0x7fb0df2c2e00] Estimating duration from bitrate, this may be inaccurate
Segmentation fault: 11

Any idea what could be causing this? I have also tried with an mp3

**Comment by piem** [comment]
hi @ErenPhayte, how did you install aubio?

**Comment by ErenPhayte** [comment]
Hi,

Will close ticket, figured out the issue, I installed the version that was currently in PIP repo. I instead downloaded GIT repo and installed that as per instructions .. it now works.

Challenge I have now is figuring out how to get data to plot a chromagram or something similar to the wave output on Soundcloud haha. Basically want to take DB levels and map the different levels to different colors.i.e. higher DB level will be red, lower will be green.

Thanks for the quick response.

**Comment by piem** [comment]
Ok. If you are running on macOS, it could be that you had a similar issue as in #103 (ffmpeg installed in both conda and brew).

To run aubio on soundcloud streams, you can `pip install youtube-dl`, then use it with `youtube-dl -xg`. For example:

    aubio onset `youtube-dl -xg https://soundcloud.com/youngpulse/b1-all-this-love-i-have`
or

    ./python/demos/demo_bpm_extract `youtube-dl -xg https://soundcloud.com/carl-cox/keepee-uppee-fatboy-slim-1`

Please feel free to open another issue if you have another question.
