### ISSUE TITLE
Peak Detection

### ISSUE THREAD

**Issue by ErenPhayte** [aubio/aubio#109]
Hi,

So I am busy trying to take an audio file and create a waveform from it. I am actually trying to use this demo

https://github.com/aubio/aubio/blob/master/python/demos/demo_waveform_plot.py

The output however will be something different. The idea is to spit out something that looks like a music sheet, with higher DB level displayed as a different geometry i.e. a noticeable drum beat, would show as a triangle, where as much lower frequencies will display dots or circles. 

Is there a way to do peak detection so that I can get all the points I really need to create the graph?
See link below of what I am looking for
[Peak detection paper](https://terpconnect.umd.edu/~toh/spectrum/PeakFindingandMeasurement.htm)

And how I want to represent that on a graph;

[Example Output](https://www.dropbox.com/s/dx5eqs7xkm9ci81/example.png?dl=0)

**Comment by ErenPhayte** [comment]
Solve:

https://github.com/MonsieurV/py-findpeaks

**Comment by piem** [comment]
ei @ErenPhayte. nice! what algorithm solved what problem?

**Comment by ErenPhayte** [comment]
I used the peakutils.peak.indexes  library. I first found an [article](https://blog.ytotech.com/2015/11/01/findpeaks-in-python/) that was published where the writer had played with various libraries and he rated the Peakutils library as one of the better ones.
