### ISSUE TITLE
Spectrogram Demo Locks

### ISSUE THREAD

**Issue by ErenPhayte** [aubio/aubio#110]
I have noticed that the spectogram crashed in while loop:

specgram = vstack((specgram,pv(samples).norm))

Any idea's why this could cause Python to fall over?

**Comment by piem** [comment]
hi @ErenPhayte,

pv should never crash. could you let us now how you installed aubio, and what program are you trying to run?

thanks, piem

**Comment by ErenPhayte** [comment]
If I recall, I used the git installation instructions
`
git clone https://git.aubio.org/aubio/aubio/
# from source directory
cd aubio
pip install -v .
`

It might be worth noting I am running a Macbook Pro Sierra. I did find if I used a smaller audio file, it works, but generally locks up the processes for a couple minutes before it completes.

**Comment by piem** [comment]
@ErenPhayte , what program are you trying to run?

Also, please make sure you have the latest version installed:
```
pip uninstall aubio -yv
pip install -Uv git+https://git.aubio.org/aubio/aubio/
```

**Comment by piem** [comment]
Hi @ErenPhayte, could you confirm this bug and provide more info about it? see also #102.

**Comment by ErenPhayte** [comment]
Not sure what happened, but is working now. It does freeze on bigger audio files, but if left alone comes right after a few minutes.
