### ISSUE TITLE
What is the "right" pitch for a whole file?

### ISSUE THREAD

**Issue by AshJRI** [aubio/aubio#115]
Hi @ all

Please excuse me, if my question seems rather stupid to an expert. But I am not an expert and "asking stupid questions is easier than fixing stupid errors" (quotation based on Heinrich Böll) ;)

I get a pitch and a confidence value for each processed "data window" (number of audio samples).
But what is the meaning of these values? Is the value only for this "data window" or for all processed samples up to the current position?
And based on that, what is the "right" way to choose a single pitch value for a longer time period or whole audio file?

Is it the last detected pitch value (which is not 0)?
Or the pitch with the highest confidence?
Or the average or median over a number of pitch values? And if so: over all pitch values or only with confidence > 0?

Thanks, AshJRI

**Comment by piem** [comment]
hi @AshJRI 

> But what is the meaning of these values? Is the value only for this "data window" or for all processed samples up to the current position?

Yes, the value is only for this "window", typically between 2048 or 4096 points.

> And based on that, what is the "right" way to choose a single pitch value for a longer time period or whole audio file?

It depends, but you could do something like that:

 - measure pitch and pitch confidence on each window
 - keep only pitch values for which the confidence is high enough
 - take the median of these values

Depending on what your looking for, you can take the median of:

 - all frames in an audio file (e. g. assuming the file contains a single note)
 - all frames between two instants (to assign a single pitch value to a segment) 
 - the last n frames (moving median filter to remove some spurious values).

Let us know if this helps!

**Comment by AshJRI** [comment]
Thanks. This helps a lot.
I think I'll do some more tests, now.
In case of typical music tracks, it may be interesting to see what happens if I cut of start and end (Based on the perception that many music tracks have lead-in/-out with different rhythm, singing begins after the lead-in and the most constant part is around the middle of a track),

Thanks a lot.
