### ISSUE TITLE
AUBIO ERROR: source_wavread: Failed opening mp3 (could not find RIFF header)

### ISSUE THREAD

**Issue by shiregator** [aubio/aubio#116]
Hi,

I downloaded aubio-0.4.5-win64.zip from (https://aubio.org/download) and am trying to run aubiotrack.exe on mp3 files, but it fails with the following error.  

C:\Users\jmulford\Downloads\aubio-0.4.5-win64.zip\aubio-0.4.5-win64\bin\aubiotrack.exe -i "01-02- Reaching - Copy.mp3"
AUBIO ERROR: source_wavread: Failed opening 01-02- Reaching - Copy.mp3 (could not find RIFF header)

Am I incorrect in thinking that all I need for this is the aubiotrack.exe and libaubio-5.dll ?  My OS is Windows 10 x64.  Is there some other setup I'm missing?  Or do I have to build aubio locally?

Thanks!
Jamie

**Comment by piem** [comment]
hi @shiregator 

The default binary is built with only a simple WAV file reader.

To read from mp3 and other formats, try the [binary build against ffmpeg](https://aubio.org/download#win). I updated the links on https://aubio.org/download#win.

You could also have a look at the vcpkg package (in preparation, see #114), or the [conda](https://anaconda.org/conda-forge/aubio) package if you are mostly interested in python-aubio.

Let us know how it goes!

**Comment by shiregator** [comment]
Hi @piem ,

Thanks for your help.  I was able to get the ffmpeg binary to work.  I'm interested in testing the beat/event detection.

For any others that might need help here are the quick steps to get that working:

1. Download your appropriate aubio-***-ffmpeg.zip from here [https://aubio.org/download#win](url)
2. Extract the contents to your desired location (i.e., C:\Utilities\aubio)
3. Follow the instructions to download ffmpeg
4. Extract the contents to your desired location (i.e., C:\Utilities\ffmpeg)
5. Follow the instructions to downlaod the Dev (or Shared if you only want to run) ffmpeg from here [https://ffmpeg.zeranoe.com/builds/](url)
6. Extract the contents to your desired location (i.e., C:\Utilities\ffmpeg)
7. Append the locations to your user Environment Variable PATH (i.e., C:\Utilities\ffmpeg\bin;C:\Utilities\ffmpeg\lib)
8. Restart your cmd window
9. Execute:
C:\Users\Utilities\aubio\bin>aubiotrack.exe -i "01-02- Reaching - Copy.mp3"
1.701451
2.011020
2.320567
2.630136
...
...
...
C:\Users\Utilities\aubio\bin>
Regards,
Jamie

**Comment by blindndangerous** [comment]
Apologies for bringing up an old issue, but I came across this when trying to use this with beets and the bpmanalyser plugin found here. https://github.com/adamjakab/BeetsPluginBpmAnalyser
I'm doing this all through windows, so following his instructions I did pip install aubio, but I'm now getting the same errors.  Is their a build of this for Windows with ffmpeg support in pip?  Or do I have the instructions wrong?

**Comment by petwri** [comment]
Same here. has anybody fixed this?

**Comment by blindndangerous** [comment]
Hey @petwri  I believe to fix this I needed to do pip3 uninstall aubio and install the version from the package repository.  However, beets has now switched to using autobpm instead of bpmanalyser so I took that part out of my notes.  It should be called python3-aubio.
