### ISSUE TITLE
Cannot persist the data in Core Data when app re-launches

### ISSUE THREAD

**Issue by nups543** [aubio/aubio#117]
I am using Core Data for the first time in a project made in XCode 8, swift 3. I have used background context (calling container.performBackgroundTask block..) to save the data and main context to fetch the data. When my app re-launches, the data I saved in the private background context is deleted.

 Please tell me where I went wrong !!!

Here I call CoreDataManager class save context method in applicationDidEnterBackground and applicationWillTerminate methods of AppDelegate class:

    class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    lazy var coreDataMgrInstance = CoreDataManager.sharedInstance

    func applicationDidEnterBackground(_ application: UIApplication) {
       
        coreDataMgrInstance.saveContext()
    }
    func applicationWillTerminate(_ application: UIApplication) {
        coreDataMgrInstance.saveContext()
    }}
Here is my Singleton class CoreDataManager to initiate NSpersistentContainer
        
    class CoreDataManager: NSObject {    
    class var sharedInstance: CoreDataManager {
        struct Singleton {
            static let instance = CoreDataManager()
        }
        
        return Singleton.instance
    }
       private override init() {

        super.init()
    }
    
     lazy var persistentContainer: NSPersistentContainer = {
       
       let container = NSPersistentContainer(name: "E_CareV2")
        
        let description = NSPersistentStoreDescription() // enable auto lightweight migratn
        description.shouldInferMappingModelAutomatically = true
        description.shouldMigrateStoreAutomatically = true
        
        container.persistentStoreDescriptions = [description]
        
        container.loadPersistentStores(completionHandler: { (storeDescription, error) in
            if let error = error as NSError? {
                fatalError("Unresolved error \(error), \(error.userInfo)")
            }
        })
        container.viewContext.automaticallyMergesChangesFromParent = true
        return container
    }()
    func saveContext(){
       
        print("saveContext")
        let context = persistentContainer.viewContext
        if context.hasChanges {
            do {
                try context.save()
            } catch {
                let nserror = error as NSError
                fatalError("Failure to save main context \(nserror), \(nserror.userInfo)")
            }
    }}
Now this is the class where I save and fetch the data from Core Data 
      
    class SenderViewController: UIViewController {

    var persistentContainer: NSPersistentContainer!
     
    override func viewDidLoad() {
        super.viewDidLoad()

     persistentContainer = CoreDataManager.sharedInstance.persistentContainer
     let results = self.fetchPersistentData(entityName: "School", withPredicate: nil)
        print("results \n \(results)")       
      }

     @IBAction func enterPressed(_ sender: Any) {
     
      self.persistentContainer.performBackgroundTask({ (backgroundContext) in
        
            backgroundContext.mergePolicy = NSMergePolicy.mergeByPropertyStoreTrump

            let schoolentity = NSEntityDescription.insertNewObject(forEntityName: "School", into: backgroundContext) as! School
                    
                    schoolentity.schoolName = "ABC"
                    schoolentity.schoolWebSite = "http://anywebsite.com/"
               
                do {
                    try backgroundContext.save()
                } catch {
                    fatalError("Failure to save background context: \(error)")
                    }
        })
    }
    
    func fetchPersistentData(entityName: String?, withPredicate: NSPredicate?) -> [NSManagedObject]{

            let context = self.persistentContainer.viewContext
            let request: NSFetchRequest<School> = School.fetchRequest()
            let newentity = NSEntityDescription.entity(forEntityName: entityName!, in: context)

            request.entity = newentity
            request.returnsObjectsAsFaults = false
            
            do {
                let searchResults = try context.fetch(request) as [NSManagedObject]
                return searchResults               
            } catch {
                print("Error with request: \(error)")
            }
     return []
    }

**Comment by piem** [comment]
hi @nups543, are you sure you posted this at the right place? i don't see how aubio is involved here! :-)

**Comment by nups543** [comment]
I am sorry. I did not check where I posted it. I am new to Github.
