### ISSUE TITLE
How to use aubioquiet in python? 

### ISSUE THREAD

**Issue by devtakle** [aubio/aubio#124]
I am trying to run the aubioquiet command. Is this a python command which can be used like 
aubio pitch , aubio onset etc? I get a syntax error when I try to run it with python in Terminal.

**Comment by fishmongr** [comment]
I ran into this too. Looks like the Python install makes "aubio" and "aubiocut" available as comand line tools but aubioonset, aubiopitch, aubiomfcc, aubiotrack, aubionotes, aubioquiet are not. Would be nice to have them all registered as command line tools. 
Reference: https://aubio.org/manual/latest/cli.html

**Comment by piem** [comment]
hi @devtakle , hi @fishmongr 

correct, the `aubio` tool is missing the `quiet` subcommand.

thanks for the report. it will be added it in the next release.

please let us know (in new issues) if you'd like to see other features.

**Comment by piem** [comment]
hi @devtakle and @fishmongr,

this should be fixed in master now. you should be able to try with:

    pip install -Iv git+https://github.com/aubio/aubio.git

best, piem
