### ISSUE TITLE
Using aubio 0.4.5 in a Windows environment

### ISSUE THREAD

**Issue by CKKOY** [aubio/aubio#129]
Dear Sir or Madam, 

I recently downloaded aubio 0.4.5 for Windows (64-bit architecture), with ffmpeg build. I would like to explore the pitch detection functionality. But I am new to aubio, C and Python. I am not sure where to begin if I want to analyse audio! 

Google searches seem to imply that aubio is run through the command line, but I'm not sure exactly how to use the command line and aubio to analyse an audio file. 

I would appreciate it if you could point me in the right direction, so I can actually start using aubio!

Yours faithfully, 

Caleb Owusu-Yianoma

**Comment by CKKOY** [comment]
hi @piem 

i will do so and let you know

regards, 

caleb

**Comment by CKKOY** [comment]
hi @piem,

i typed the following into both the Windows cmd and the Python command line:

`aubioonset -h`

cmd returned:

`'aubioonset' is not recognized as an internal or external command, operable program or batch file.`

in the Python command line, the following was returned:

```
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
NameError: name 'aubioonset' is not defined
```

i'm not sure exactly what these mean or how i can solve them, but i'm updating you on progress while i research these errors and try to solve them myself! (if you do see them before i send the next update, i'd appreciate any help.)

regards,

caleb

**Comment by piem** [comment]
My bad, I guess the `.exe` extension is required in windows `cmd`, so:

    aubioonset.exe -h

If you are interested in the python module, have a look at the [conda-forge package](https://anaconda.org/conda-forge/aubio).

**Comment by CKKOY** [comment]
thanks!

**Comment by CKKOY** [comment]
hmm.. i tried it but that also didn't work!

**Comment by CKKOY** [comment]
i think it's an environment variable issue. i'm going to try and change the path to the aubio folder that was created when i installed it, then try and run the `aubioonset.exe -h` command in `cmd` again

**Comment by piem** [comment]
Unfortunately, *didn't work* won't help. Please [elaborate](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)! :-)

**Comment by CKKOY** [comment]
sure!

**Comment by CKKOY** [comment]
The result I got was: 

`'aubioonset.exe' is not recognized as an internal or external command, operable program or batch file`

**Comment by CKKOY** [comment]
i've had a similar issue when trying to call up other installed programs from `cmd`, and a Google search revealed that it is likely to be an environment variables issue

**Comment by CKKOY** [comment]
so i'm currently adding the file path for aubio to the PATH section in the Windows Environment Variables dialog box

**Comment by piem** [comment]
Did you run it from the directory containing `aubioonset.exe` ? If yes, i would try `./aubioonset.exe`.

Sorry, no windows shell at hand right now.

**Comment by CKKOY** [comment]
Hi, Paul. 

So, I've noticed a few things:

1. There is no file named `aubioonset.exe` in any of the sub-directories under the aubio-0.4.5 directory .
2. When I navigate to the directory `aubio\source\onset` (under `C:\Users...`) and then type the command `aubioonset.exe -h`, I get the same error (see comments above) about that not being recognized as a command, operable program or batch file
3. I think the issues might be because I'm not fully understanding the process of downloading/installing and then getting aubio running.

**Comment by piem** [comment]
@CKKOY it seems you are looking at the source code for aubio.

Please download [aubio **binary** for windows](https://aubio.org/download#win) and try again.

**Comment by CKKOY** [comment]
@piem, I will do so. Thank you.

**Comment by CKKOY** [comment]
I've downloaded the `aubio-0.4.5-win64-ffmpeg.zip` binary. When I try to run `aubioonset.exe`, I get the system error: 'The program can't start because avcodec-57.dll is missing from your computer. Try reinstalling the program to fix this problem. This might be because I need to download the ffmpeg build, so I'll do that now.

**Comment by piem** [comment]
@CKKOY start without ffmpeg first, or download ffmpeg and place the dlls in the same folder next to aubioonset.exe.

**Comment by CKKOY** [comment]
@piem, I removed `aubio-0.4.5-win64-ffmpeg.zip` and have downloaded w/o ffmpeg.

**Comment by CKKOY** [comment]
I clicked the aubioonset.exe file and got it to run.

**Comment by CKKOY** [comment]
Then I opened `cmd`, navigated to the directory containing `aubioonset.exe` and then ran the command `aubioonset.exe -h` and got the attached.
![20170825aubioscreenshotv1 1coy](https://user-images.githubusercontent.com/13520810/29723897-496f62fe-89be-11e7-8fb8-4ee65239d20d.png)

**Comment by CKKOY** [comment]
So I think it's working now!

**Comment by piem** [comment]
Yes, looking good! Let us know if you have more questions. I'll let you close that bug when you're set.

**Comment by CKKOY** [comment]
Thanks, @piem. I'll close it now.
