### ISSUE TITLE
StandardError: error creating object

### ISSUE THREAD

**Issue by DaleEMoore** [aubio/aubio#13]
I'm a new user and followed the installation procedures

```
http://aubio.org/download
http://aubio.org/installation
```

Then I got "Failed modules"

```
Python 2.7.5+ (/usr/bin/python2.7)
aubio._aubio
Generation of skeletons for the modules above will be tried again when the modules are updated or a new version of generator is available.

fixed with
updatedb
locate libaubio.so
pushd /usr/lib
ln -s /usr/local/lib/libaubio.so.4 .
```

I figured I'd test my installation with your script from 

```
https://github.com/piem/aubio/blob/master/python/scripts/aubiocut but I get:
```

But I get this error

```
/usr/bin/python2.7 /home/dalem/PycharmProjects/elapsedbeats/aubiocut.py Fr-grenouille.ogg
Unable to import Numpy array from aubio module (error -1)
AUBIO ERROR: source_wavread: could not find RIFF header in Fr-grenouille.ogg
AUBIO ERROR: source: failed creating aubio source with Fr-grenouille.ogg at samplerate 0 with hop_size     256
Traceback (most recent call last):
  File "/home/dalem/PycharmProjects/elapsedbeats/aubiocut.py", line 152, in <module>
    s = source(source_file, samplerate, hopsize)
StandardError: error creating object
```

I wonder if you have any insight into how to get around this issue on:

```
root@QnD:/usr/lib# cat /etc/issue
Ubuntu 13.10 \n \l
```

**Comment by tiennth** [comment]
Hi, i just found this guide above to build aubio with avcodec enable. 
My question is how to build aubio for iOS with avcodec enable, using script file "scripts/build_apple_frameworks"?
I have tweak that file and enable avcodec option, but i got some errors as below:

`ld: warning: ignoring file /usr/local/Cellar/ffmpeg/3.0.2/lib/libavcodec.dylib, file was built for x86_64 which is not the architecture being linked (arm64): /usr/local/Cellar/ffmpeg/3.0.2/lib/libavcodec.dylib
ld: warning: ignoring file /usr/local/Cellar/ffmpeg/3.0.2/lib/libavformat.dylib, file was built for x86_64 which is not the architecture being linked (arm64): /usr/local/Cellar/ffmpeg/3.0.2/lib/libavformat.dylib
ld: warning: ignoring file /usr/local/Cellar/ffmpeg/3.0.2/lib/libavresample.dylib, file was built for x86_64 which is not the architecture being linked (arm64): /usr/local/Cellar/ffmpeg/3.0.2/lib/libavresample.dylib
ld: warning: ignoring file /usr/local/Cellar/ffmpeg/3.0.2/lib/libavutil.dylib, file was built for x86_64 which is not the architecture being linked (arm64): /usr/local/Cellar/ffmpeg/3.0.2/lib/libavutil.dylib
`
Thanks in advance,

**Comment by piem** [comment]
Hi @tiennth ,

I will open a new issue for this.

Best, Paul
