### ISSUE TITLE
Can I get the millisecond value of an note onset detection converted to ms since 1970?

### ISSUE THREAD

**Issue by simonator123** [aubio/aubio#130]
As far as I can tell, I can only obtain the millisecond value of an onset detection relative to when I started processing audio data. Is there any way to get the millisecond value relative to a certain date? For example, in iOS, you can use the number of milliseconds since 1970.

**Comment by piem** [comment]
hi @simonator123 

yes, this should be fairly easy:

1. get the current time just before entering the processing loop (using `gettimeofday` or similar)
2. add to that time the time you get from `aubio_onset_get_last_s()`

Ideally, system calls such as `gettimeofday` should be avoided in the processing loop.

let us know if this answers your question,

best, piem

**Comment by simonator123** [comment]
I'm having some trouble finding the exact spot I need to do this. Let me give you a little background first. I'm making a rhythm application which tells the users how accurately they are playing along to the rhythm. What I am doing currently is getting the current timestamp right after I determine that a note onset is present. So, right after is_onset is true in the following code:

aubio_onset_do (aubioOnsetObject, inputBuffer, onset);
        let is_onset = fvec_get_sample(onset, 0);

I then get the difference between that timestamp value and the correct ms timestamp for the note supplied to me by the music API I am using. This is actually working pretty darn well. I then use this to visually indicate playback accuracy. The onset value for the metronome playback (should be spot on) compared to the correct onset ms value has a difference between 20ms and 30ms. While this is pretty good, I want it to be better, and I know it can be better because the playback timestamp I am using is *after* the point in time of which aubio determines that an onset is present. So, that is why I am trying to use the ms value supplied to me by aubio in reference to 1970 because that is a common point that aubio and the music API can be compared against. 

How does aubio calculate the ms value for the note onset? What is the value relative to? The first input buffer value received? So, do I need mark my relative timestamp right before my app starts recording? 

Here are the calls that I am making:

1. _(set onset object)_
        aubioOnsetObject = new_aubio_onset ("hfc", 512, 256, 44100)
        aubio_onset_set_silence(aubioOnsetObject, -20)

2. Start recording: _audiounit stuff_
3. _(prepare fvec with audio input buffer data)_
           let inputBuffer = new_fvec(frameCount)      
            for i in 0..<count
            {
                let x = Float(dataArray[i])
                inputBuffer?.pointee.data[i] = x
            }
            onsetManager.getOnset(inputBuffer)

4 _(determine if there is an onset)_
      aubio_onset_do (aubioOnsetObject, inputBuffer, onset);
        let is_onset = fvec_get_sample(onset, 0);

So, would my timestamp need to be right before I start recording (number 2)?

**Comment by piem** [comment]
hi @simonator123 

You could get the timestamp at the end of 2., when audiounit initialization is done. Or even in the first time the processing function is run.
 
What music API you are using? It would be more accurate to count the total number of samples played back from the beginning of the process.

**Comment by simonator123** [comment]
okay, I might be able to use an audio unit unit callback. 

I'm using the SeeScore sdk. Right before the note is played by SeeScore, I get a callback, which is where I get the timestamp for what the correct value is. I compare this value to what aubio detects when the user plays along. 

Part of what makes pinpoint accuracy difficult here is that there is some inconsistency in the current setup with the timing of when the note callback handler is called. Then, if I try your approach of counting samples since the beginning of the "process", Im not sure I would be able to coordinate the start of the aubio process with the start of the SeeScore playback process.

Can I request an addition to aubio onset process? Would it work allow the option of returning a ms note onset timestamp relative to some date?

**Comment by piem** [comment]
@simonator123 could the problem partly come from:

> some inconsistency in the current setup with the timing of when the note callback handler is called ?

i'm not sure why you would require calling `gettimeofday` from within aubio, but examples and patches are always welcome!

best, piem

**Comment by simonator123** [comment]
i think the problem is that some things (callback, onset handling maybe?) are not happening on the iOS realtime thread, and so there will naturally be some ms timing inconsistency. Like I said, though, it's pretty good, but I think it could get just a little bit better. 

So, would you be willing to provide a patch where the note onset timing is returned as a timestamp since some reference date, Jan 1, 2001 midnight, for instance? The reason I ask for this is that this might gain me a millisecond or more accuracy because I don't have to calculate the timestamp after the onset is actually detected, it comes right from the source.

**Comment by piem** [comment]
@simonator123 When using `aubio_get_last_s`, an [interpolation](https://github.com/aubio/aubio/blob/master/src/onset/onset.c#L79) is made to find the best location *before* the current time.

This interpolation creates a variable delay, maybe that's causing you troubles. Instead of using `aubio_onset_get_last`, try using `aubio_onset_do(..) != 0` to see if it helps.

**Comment by simonator123** [comment]
Cool. I will give it a shot! I'll let you know how it turns out.

**Comment by simonator123** [comment]
Okay, so, it's actually looking like there might not be much I can do with the source, but I think there might be a way that I can improve my own timestamp value. Take a look at my code (I put the 
 text 'PAUL' in the key spot in each file). I process the mic data in AudioManager and send it to OnsetManager to determine if it is an onset; if it is, the execution continues elsewhere.

[AudioManager.txt](https://github.com/aubio/aubio/files/1269518/AudioManager.txt)
[OnsetManager.txt](https://github.com/aubio/aubio/files/1269519/OnsetManager.txt)

When I compare the ms value obtained via `aubio_get_last_ms + (ms_time_stamp_value_at_start_time)`, the time is much greater than the ms value obtained when I just get the timestamp after 
`aubio_onset_do != 0` (like it currently is in the code). 

Theoretically, using `aubio_get_last_ms + (ms_time_stamp_value_at_start_time)` should give me a timestamp value that is less than the current timestamp obtained after `aubio_onset_do != 0`, but I couldn't get this to work. Might this be because of the different function and object calls that are occurring during the mic data processing? I'm wondering if I should put all of my code in 

`let recordingCallback: AURenderCallback = {...}` That might enable me to use the 

`aubio_get_last_ms + (ms_time_stamp_value_at_start_time)` method (which hopefully would give me a ms timestamp value before my current 

`aubio_onset_do != 0` method).

Am I making any sense? What do you think?

**Comment by piem** [comment]
Hi @simonator123 

Did you make any progress on This? I guess you have found by now that the delay with which onset timestamps are emitted can be adjusted with [`aubio_onset_set_delay_*`](https://aubio.org/doc/latest/onset_8h.html#ac9d999003443d04dc0f3a15aa0df7613).

**Comment by simonator123** [comment]
Hi @piem, I am no longer having any issues. The developer of SeeScore was able to give me the exact timestamp at when each note is played back via dispatch_time_t. This helped incredibly. Now I am just using the dispatch_time_t at which the note onset is obtained and I compare the two values: the value at which the note should be played back, and the time at which the onset is obtained. It works beautifully! I can determine accuracy down to about an average of 4 ms.

**Comment by piem** [comment]
Excellent! Looking forward to try it! :-)

**Comment by qky1412** [comment]
> Hi @piem, I am no longer having any issues. The developer of SeeScore was able to give me the exact timestamp at when each note is played back via dispatch_time_t. This helped incredibly. Now I am just using the dispatch_time_t at which the note onset is obtained and I compare the two values: the value at which the note should be played back, and the time at which the onset is obtained. It works beautifully! I can determine accuracy down to about an average of 4 ms.

Hi, I am using SeeScore too, can you tell me the relationship between "dispatch_time_t it gives us in startNotes callback " and the current time? I don't know how to match these data, thx!

**Comment by simonator123** [comment]
Does this help? https://stackoverflow.com/questions/31792306/in-swift-how-can-i-get-an-nsdate-from-a-dispatch-time-t

What is your app? I'm curious. My app is released now, and it's called DrumToolz.

**Comment by qky1412** [comment]
@simonator123 thx for your reply. I'm just starting an app that will show music sheet & detect pitch correction when playing the piano/violin. Everything is new to me, from MusicXML's display to audio analysis, I'm wondering if current choice(SeeScore + Aubio) is best practice. And it would be very kind of you to explain some more details about pitch detection combining SeeScore. Since it's a little bit beyond current issue topic, may I contact u through email?

**Comment by simonator123** [comment]
Yea, let's continue this by e-mail. I don't want to post my e-mail on here. You can find my app's e-mail by going to drumtoolz.com and scrolling to the very bottom of the page. Send an e-mail to there, and then we will continue over my personal e-mail.
