### ISSUE TITLE
error running python/demos/demo_alsa.py

### ISSUE THREAD

**Issue by eskimoquinn** [aubio/aubio#131]
I am trying to run the demo_alsa.py demo to capture frequency from my USB device and there is a traceback like the following:

```Starting to listen, press Ctrl+C to stop
Traceback (most recent call last):
  File "demo_alsa.py", line 38, in <module>
    freq = pitcher(samples)[0]
ValueError: input size of pitch should be 1024, not 512
```

Any ideas?

**Comment by eskimoquinn** [comment]
If I change win_s to 4096, this error is replace by another: 
```
alsaaudio.ALSAAudioError: Capture data too large. Try decreasing period size
```

**Comment by eskimoquinn** [comment]
If this helps, amixer shows the following:
```
Simple mixer control 'Mic',0
  Capabilities: cvolume cvolume-joined cswitch cswitch-joined
  Capture channels: Mono
  Limits: Capture 0 - 37
  Mono: Capture 15 [41%] [-0.71dB] [on]
```

**Comment by piem** [comment]
hi @eskimoquinn 

If i'm not wrong, python alsaaudio is somewhat limited, since the buffer size depends on your soundcard.

Have a loook at [`python/demos/demo_tapthebeat.py`](https://github.com/aubio/aubio/blob/master/python/demos/demo_tapthebeat.py), which uses [pyaudio](https://people.csail.mit.edu/hubert/pyaudio/) to register a callback function.

Using pyaudio means adding a requirement on portaudio, but your code should also be more portable.

Let us know how it works for you,

best, piem

**Comment by piem** [comment]
hi @eskimoquinn 

did that solve your problem?

cheers, piem

**Comment by eskimoquinn** [comment]
It did not. I am still getting the same errors no matter what I set my settings to. 

If you look at this gist, the script records the file as I would expect, but I cannot get the frequencies.
https://gist.github.com/eskimoquinn/339ecc57fdeb3dc7f4cd18aa18d79b0b

I  am still seeing 0.0
0.0

```
Traceback (most recent call last):
  File "/home/pi/code/audioInput/audioInput.py", line 36, in <module>
    data = stream.read(CHUNK)
  File "/usr/local/lib/python2.7/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
IOError: [Errno -9981] Input overflowed 
```

**Comment by piem** [comment]
hi @eskimoquinn 

aubio is expecting floats, not ints. The gist you sent works fine here after changing `FORMAT` to `pyaudio.paFloat32`.

**Comment by eskimoquinn** [comment]
JackPot! Thanks!

**Comment by piem** [comment]
closing this issue, please re-open as needed.

cheers, piem
