### ISSUE TITLE
Aubiocut is outputting empty files

### ISSUE THREAD

**Issue by sshussain270** [aubio/aubio#132]
I am writing a python application where I need to split an audio file containing music into multiple files on per beat basis. I am doing this using Aubio library to do this (https://github.com/aubio/aubio) using its command called Aubiocut (https://aubio.org/aubiocut).

Here is the actual command I run at commandline on the file called file.mp3

> aubiocut -i file.mp3 -c -b -o Output

The command splits the original audio file into multiple files but in the resulting files, only the first file has the first beat and rest of the files are empty. The expected result was each file containing one beat from the original music file.Any idea why rest of the files are empty. Any suggestions would be highly appreciated.
-- | --

**Comment by piem** [comment]
hi @sshussain270 

what does the list of time stamp look like? could you post your input somewhere?

thanks, piem

**Comment by sshussain270** [comment]
Hi @piem !

Thanks for your reply. Yes. I have attached a zip file containing my orignal file and the resulting split up file. Could you have a look please?

The command that I ran was: `aubiocut -i file.mp3 -c -b -o Output`

I have attached a zip file containing my orignal file and the splitted files here: https://www.dropbox.com/s/rtt27vq8qhubuwg/Aubio-Test.rar?dl=0

Looking forward to hearing from you.

Thanks.

**Comment by piem** [comment]
i can't seem to open that file (no errors but the file fails to extract).

could you upload the original again as mp3 or zip?

thanks, piem

**Comment by piem** [comment]
@sshussain270 any chance you could re-up the mp3 file?

**Comment by sshussain270** [comment]
Hi Piem, I have managed to solve the issue. The problem was with my system setup and not Aubio that it wasn't playing audios of the files being created. I appreciate your help though :)
