### ISSUE TITLE
How best to study source code for pitch-detection algorithms

### ISSUE THREAD

**Issue by CKKOY** [aubio/aubio#133]
Hi, everyone.

I recently downloaded aubio and would like to study how exactly the pitch-detection algorithms (PDAs) work and have been built into aubio. I'd like to do this with the ultimate aim of learning how to implement my own real-time PDA (one that takes as input real-time audio and then analyses the pitch of the input).

My assumption is that I need to start by studying the source code used to build the PDAs. 
I've started by looking through the files in [`aubio/src/io`](https://github.com/aubio/aubio/tree/master/src/io), but I'm not sure if this is the best way to achieve my goal (especially as this is my first time analysing the source code of any piece of software, _and_ I'm not sure what all the many files in the master branch mean and which are relevant to my goal; I'm new to this all!). 

Could you point me in the right direction or suggest the best course of action to start towards my goal of understanding how the PDAs work and how they interact with aubio as a whole (i.e., their dependencies on and interconnectedness with other aspects of the source code)?

Regards, 

CKKOY

**Comment by CKKOY** [comment]
@piem, do you have any suggestions, please?

Regards, 

ckkoy

**Comment by piem** [comment]
hi @CKKOY 

all pitch algorithms are in `src/pitch` (`src/io` is only for file reading). 

you might also want to read https://aubio.org/phd

best, Paul

**Comment by CKKOY** [comment]
Hi, @piem.

I'll try look at `src/pitch` and the link you embedded. 

Regards, 

Caleb
