### ISSUE TITLE
Detecting note length using Python module 

### ISSUE THREAD

**Issue by iamvidge** [aubio/aubio#134]
Hello,

I was wondering if you had a demo for detection of note length (quarter notes, half notes), like passing in files and getting out the different note lengths and the times that they happen at since you already have a demo for detecting bpm and tempo. 

Thank you!

**Comment by piem** [comment]
hi @iamvidge 

For now notes are detected based on onsets and silence, not on tempo. It should be fairly easy to 'clamps' the notes start to detected beats (or sub-beat divisions).

**Comment by iamvidge** [comment]
Thank you @piem In other words, would aubio be capable of turning wav files into midi files? Could you give me an example of that?

**Comment by piem** [comment]
i was planning to add a demo for this, but maybe you have one ready? :-)

**Comment by iamvidge** [comment]
Unfortunately, I don't, sorry :( , but I found tutorials that are easy to use, and will get the job done (without aubio, sadly). I can give you the link if you like, if you think that that would make the demo thing easier :D .

**Comment by iamvidge** [comment]
The link is here: http://www.justinsalamon.com/news/convert-audio-to-midi-melody-using-melodia

**Comment by piem** [comment]
@iamvidge i've just added a [simple demo](https://github.com/aubio/aubio/blob/master/python/demos/demo_wav2midi.py) using [mido](https://mido.readthedocs.io/).

Let us know how it works for you!

**Comment by iamvidge** [comment]
It’s great – thank you!

Vijay
