### ISSUE TITLE
aubio_tempo_get_last_tatum should return sint_t

### ISSUE THREAD

**Issue by aybe** [aubio/aubio#152]
https://github.com/aubio/aubio/blob/25db68c4eefe354f18c58a47eeb5643fc534eb81/src/tempo/tempo.c#L265

**Comment by piem** [comment]
hello @aybe,

same as #151, but here even more so, because the tatum position should be computed with more precision than a single sample. At 44100Hz, it may sound useless, but when down-sampling to 8kHz, that would quite a bit of jitter.

so i'm closing this. feel free to re-open or comment on it.

best, piem

**Comment by aybe** [comment]
What I meant by this is that since you subtract [`last_tatum`](https://github.com/aubio/aubio/blob/25db68c4eefe354f18c58a47eeb5643fc534eb81/src/tempo/tempo.c#L52) and [`delay`](https://github.com/aubio/aubio/blob/25db68c4eefe354f18c58a47eeb5643fc534eb81/src/tempo/tempo.c#L51) and both are integral types, it didn't make sense to return an `smpl_t` because there wouldn't be any decimals.

That said, you'll be the judge on this whether they shouldn't be integral types on `_aubio_tempo_t`, what would require reviewing all the parts using them.

**Comment by autoantwort** [comment]
So the plan is to make delay a float so that you can set it to a sub sample value if you have only 8Hz or something similar? Currently it makes no sense, that `aubio_tempo_get_last_tatum` returns a `float` and not a `int`, in my opinion.

**Comment by autoantwort** [comment]
A problem is, that 16777216 is the largest float where sample precision is given.  
float(16777216) => 16777216  
float(16777217) => 16777216  
And a sample at 16777216 is just 16777216/44100/60 = 6 minutes after the analysis stats.
