### ISSUE TITLE
statistical post processing on aubiotrack results

### ISSUE THREAD

**Issue by corradocampisano** [aubio/aubio#153]
Hello,

I was reviewing aubio tools and did some statistical analysis on the results from this:

     aubiotrack -s -35 -v -i Sinead\ O\'Connor\ -\ Downpressor\ Man.mp3 > Sinead\ O\'Connor\ -\ Downpressor\ Man.beats.txt

here's the raw output (beat timings, one entry per line):
[Sinead O'Connor - Downpressor Man.beats.txt](https://github.com/aubio/aubio/files/1535907/Sinead.O.Connor.-.Downpressor.Man.beats.txt)

I then imported the data into a spreadsheet and started doing some analysis:
[aubio-test.ods.zip](https://github.com/aubio/aubio/files/1535912/aubio-test.ods.zip)

Just using the [MODE](https://help.libreoffice.org/Calc/Statistical_Functions_Part_Four#MODE) stats function, it seemed BPM is around 48:

![stats - 1 - simple stats](https://user-images.githubusercontent.com/25619972/33672982-e454b470-daab-11e7-90a2-acdd2130fec4.png)

The, using the [FREQUENCY](https://help.libreoffice.org/Calc/Array_Functions#FREQUENCY) function, that seemed even more evident:

![stats - 2 - using frequency](https://user-images.githubusercontent.com/25619972/33673230-871e897e-daac-11e7-9cf5-2548edb234e0.png)

Here's a more detailed view:

![stats - 3 - results](https://user-images.githubusercontent.com/25619972/33673248-91cd586e-daac-11e7-9d35-f5eb5f426364.png)

Is there any way to add such post processing to aubiotrack?

Here's how the audio looks like in audacity:

1) it starts with a rhythmical variation:

![audacity - 1 - variations in beginning](https://user-images.githubusercontent.com/25619972/33673380-db714d04-daac-11e7-8bee-c4b971f5fb98.png)

2) it goes to steady state:

![audacity - 2 - steady state](https://user-images.githubusercontent.com/25619972/33673410-ebe28fd6-daac-11e7-8814-c20906cebb81.png)

3) but there are more variations along the way:

![audacity - 3 - more variations](https://user-images.githubusercontent.com/25619972/33673431-fc0b38d6-daac-11e7-816c-b1cd5e5f5da1.png)

My approach was just to take the time interval (differences) between two subsequent "beats": since that should stay constant (at least for a rhythmically homogeneous section of a song), it make sense to go and look for the "most common value", hence the [MODE](https://en.wikipedia.org/wiki/Mode_(statistics)).

Would you say it is feasible and/or meaningful?

Cheers,
Corrado.

**Comment by piem** [comment]
Hi @corradocampisano 

A similar approach is used in `aubio tempo` (also in `python/demos/demo_bpm_extract.py`). The median of all intervals between consecutive beat candidates is used to compute the overall tempo. Try out the python module, and please do reopen this issue if you need anything else.
