### ISSUE TITLE
ChromaPrint failure on small files

### ISSUE THREAD

**Issue by Phreak87** [aubio/aubio#156]
Hello,

by using the Chromaprint feature with 2 Files (1st 10MB, 2230 Hashes ; 2nd 500KB, 38 Hashes as a  Snippet from file 1) 
i can get the features for both files. 
Calculation gives 125 colliding keys. 
But if i try to compare i get an index out of range exception with index = "-218" 
in Aurio.Matching.Fingerprint.Fingerprint

On larger files theres no problem.

maybe i do something wrong. 
the feature i like to implement should work like shazam 
with short sound snippets from microphone.

**Comment by piem** [comment]
hi @Phreak87 

it seems this issue should be against [Aurio](https://github.com/protyposis/Aurio), not aubio. please reopen if i missed something.

cheers, piem
