### ISSUE TITLE
A question about pitch detection speed

### ISSUE THREAD

**Issue by orpris12** [aubio/aubio#157]
Hi ! Thanks for a great library.
I was thinking, is there any way I could speed up the pitch detection process in the python library? 
I am currently trying to analyze a 3 minute song, and it takes about 30 seconds.
Thanks in advance !

**Comment by piem** [comment]
hi @orpris12, hi @moshesar,

This sounds quite slow indeed. What platform are you on? Do you have aubio 0.4.6 installed? What python version are you using? Which pitch method are you using?

`yinfast` should be significantly faster than `yin`, but slightly slower than `yinfft`. You could also use less computationally intensive methods such as `fcomb` or `schmitt`, but at the expense of less accuracy.

To further speed things up, you may want to try downsampling the signal to a lower sampling rate:

```
$ time aubio pitch -r 48000 python/tests/sounds/48000Hz_60s_sweep.wav -q -m yin

real    0m1.685s
user    0m1.752s
sys     0m0.244s

$ time aubio pitch -r 8000 python/tests/sounds/48000Hz_60s_sweep.wav -q -m schmitt

real    0m0.560s
user    0m0.628s
sys     0m0.252s
```

Running `aubio pitch -m yinfast -r 44100` on a 7 minutes long mp3 takes about 7 seconds on my ageing laptop.

best, piem

**Comment by piem** [comment]
hi @orpris12, i hope I answered your questions. Please re-open providing more information if needed.
