### ISSUE TITLE
Real time audio processing

### ISSUE THREAD

**Issue by magnus-gross** [aubio/aubio#162]
Is there an easy way how I can use aubio to do real-time audio processing? I only found ways to do e.g. pitch detection on existing files.
Any ideas how I can use aubio if I don't want to write my entire audio to a file, i.e. keep it just in a local buffer? Is that possible at all?

**Comment by piem** [comment]
hi @magnus-gross 

There are many ways to use aubio in real-time. On linux, you can use the command line tools with JACK to run them in real time. Take a look at the files in `examples/` for code snippets in C.

You can also process audio in real-time with the python module. Have a look in `python/demos/demo_tapthebeat.py` for instance.

**Comment by magnus-gross** [comment]
I didn't see the jack example in examples.
However, I think that still isn't what I am looking for.

If I understand correctly, this implements the audio capturing on its own.

The thing is, that I use the Qt framework to do all my cross platform stuff. So I also use Qt to do the Audio caputring which works in a cross platform way, i.e. it also works on Android and not only on Linux.

So I guess my question would rather be whether it is possible to do audio processing on audio that I already have captured into a buffer, but which happens in real time, i.e. I don't necessarily want to write everything into a file. So I don't want to actually capture the audio, I just want to do the audio processing part with aubio (pitch detection).

Do you think this is still possible?

**Comment by piem** [comment]
yes, aubio was designed for this. Here are the steps to follow:

### prepare audio thread

1. create aubio objects before entering the audio processing thread
2. delete these objects when the audio thread exits

### update audio thread

1. in your audio processing function, copy (or point) the samples coming from Qt into an aubio `fvect_t`
1. still in your audio processing function, execute the aubio_..._do function
1. do something with the results!

That should be enough. Let us know how it goes.

**Comment by magnus-gross** [comment]
This sounds great!
Thanks for explaining. :)

There is one more thing that is unclear to me:

If I feed the audio to aubio in the `fvect_t` format, what audio format does aubio expect exactly? Like how does aubio know which encoding is used?

Again, sorry for bothering you and thanks for your time.

**Comment by piem** [comment]
aubio expects an array of `float*` containing a `hop_size` samples.

In [pd-aubio](https://aubio.org/pd-aubio), you can find [examples](https://github.com/aubio/pd-aubio/blob/master/src/aubiotempo~.c#L40-L56) of how the samples can be copied from the input array into an `fvec_t`.

**Comment by magnus-gross** [comment]
Thanks for your advice!

Using your explanation, I was now [able to implement it!](https://github.com/magnus-gross/quickpitch/blob/master/src/pitchbuffer.cpp#L13-L16). :)
It works really well :+1: 

I just chose the hop_size and buffer_size, like in one of your examples:
```
#define BUF_SIZE 2048
#define HOP_SIZE 512
```

Do you know a good source where I can read about, what effect these values have?

**Comment by piem** [comment]
Excellent!

`hop_size` simply defines the rate at which the pitch analysis is being computed. `buf_size` instead has a strong impact on the accuracy of the pitch estimates, especially in the low frequency.

You will find a discussion of how these parameters influence the results in Chapter 3 of [this document](https://aubio.org/phd).

**Comment by magnus-gross** [comment]
You have to somehow record audio and provide that audio data to aubio. Usually you will use a library, in this case I used Qt which is a C++ library. However, you could also use Qt with Python, since Qt has Python bindings as well. There are probably some python only audio recording libraries as well, you just have to search and there is also a Linux only recording example in the source tree of aubio I think.
