### ISSUE TITLE
Use pytest for python module tests

### ISSUE THREAD

**Issue by dvzrv** [aubio/aubio#163]
Title says it all: It would be awesome to use pytest instead of nose2 in the tests, as nose2 is only in maintenance release mode.

I'm currently packaging aubio for Arch Linux and would rather not pick up yet another test suite from the [AUR](https://aur.archlinux.org/) to be able to provide a check() function for aubio's build script.

**Comment by piem** [comment]
hi @dvzrv 

Thanks for your work on packaging aubio for arch.

We are not really far from being able to run the test suite in `pytest`. Most of the tests already pass in `pytest`, the only feature missing is nose's `@params` decorator, but reading the following page, it shouldn't be to hard to port:

> https://docs.pytest.org/en/latest/example/parametrize.html

Making nose2 optional would be nice indeed. A PR would be most welcome, of course. :)

**Comment by piem** [comment]
hi there,

just to mention that I've just pushed a branch `feature/pytest` where i started updating the tests.

Running `pytest` should work in that branch, but it will take a few more iterations before all continuous integrations tests pass on all platforms.

Suggestions and patches welcome!

cheers, piem
