### ISSUE TITLE
`aubio --version` prints `aubio: error: too few arguments`

### ISSUE THREAD

**Issue by lgarron** [aubio/aubio#165]
Repro:

   > pip install aubio
    > aubio --help
    usage: aubio [-h] [-V]  ...

    optional arguments:
      -h, --help     show this help message and exit
      -V, --version  show version

    commands:

        help         show help message
        onset        estimate time of onsets (beginning of sound event)
        pitch        estimate fundamental frequency (monophonic)
        beat         estimate location of beats
        tempo        estimate overall tempo in bpm
        notes        estimate midi-like notes (monophonic)
        mfcc         extract Mel-Frequency Cepstrum Coefficients
        melbands     extract energies in Mel-frequency bands
        quiet        extract timestamps of quiet and loud regions
        cut          slice at timestamps

    use "aubio <command> --help" for more info about each command

    > aubio --version
    usage: aubio [-h] [-V]  ...
    aubio: error: too few arguments

Same with `-V`.
I don't know whether the documentation is out of date or there is a bug, but I thought I'd report.

**Comment by piem** [comment]
hi @lgarron 

thanks for your report. I noticed this behavior when writing `python/lib/aubio/cmd.py`, and I believe this is a bug in python's `argparse`.

Now, I just tried reproducing it, but couldn't, so it seems this has been fixed in most recent versions of python:

    $ python --version
    Python 3.5.3
    $ aubio --version
    aubio version 0.4.7~git+3d559cee+mods

Note that with python 2, the bug is still there:

    $ python --version
    Python 2.7.9
    $ aubio --version
    usage: aubio [-h] [-V]  ...
    aubio: error: too few arguments

Tagging this issue as `wontfix`, since there is not much we can do about it.

@lgarron which version of python are you using?

cheers, piem

**Comment by lgarron** [comment]
> @lgarron which version of python are you using?

Probably 2 at the time. I keep having to switch my `$PATH` back and forth to accommodate different programs that expect the default version of Python to be 2 vs. 3. :-/

Right now, I have Python 3 in my path, and it seems to work!

    lgarron@Euclid ~> aubio --version
    aubio version 0.4.6
    lgarron@Euclid ~> python --version
    Python 3.6.4

**Comment by piem** [comment]
@lgarron ok, great, thanks for the feedback.

I couldn't find the corresponding bug in the python bug tracker, but it seems pretty clear.

About switching path: i tend to prefer python 3 as much as possible nowadays, but if I need python 2 (for instance to test aubio in both versions), i usually create 2 virtualenvs one directory higher:

    virtualenv -p `which python3` mypyenv3
    virtualenv -p `which python2` mypyenv2
    git clone https://github.com/aubio/aubio.git
    cd aubio/

 and use the `activate` script to switch from one to the other:

    source ../mypyenv3/bin/activate
    # change something and check all tests pass
    pip install -Iv . && ./python/tests/run_all_tests
    # switch to py2 and check all tests pass there too
    source ../mypyenv2/bin/activate
    pip install -Iv . && ./python/tests/run_all_tests
    # go back to py3
    source ../mypyenv3/bin/activate

cheers, piem
