### ISSUE TITLE
filterbank do method

### ISSUE THREAD

**Issue by russellb23** [aubio/aubio#172]
I am trying to compute filterbank with filterbank.do method. Even after importing filterbank and initializing the object as follows, do method doesn't appear as a method. However, the documentation says it has a do method. Any help?

I am using aubio as a python library.

``from aubio import filterbank``
``f = filterbank(n_filters, win_s)``
``s = f.do(...)``

**Comment by piem** [comment]
hi @russellb23 

`_do` methods in C are mapped to `__call__` methods in python. so something like this should work better:

    from aubio import filterbank
    f = filterbank(n_filters, win_s)
    s = f(...)

see also more examples in [python/demos](https://github.com/aubio/aubio/blob/master/python/demos).

 - [demo_filterbank.py](https://github.com/aubio/aubio/blob/master/python/demos/demo_filterbank.py)
 - [demo_filterbank_slaney.py](https://github.com/aubio/aubio/blob/master/python/demos/demo_filterbank_slaney.py)
 - [demo_filterbank_triangle_bands.py](https://github.com/aubio/aubio/blob/master/python/demos/demo_filterbank_triangle_bands.py)
 - [demo_mel-energy.py](https://github.com/aubio/aubio/blob/master/python/demos/demo_mel-energy.py)

let us know if this helps!

**Comment by russellb23** [comment]
Thank you @piem . I get that now. What I intend to do is separate the input signal into several frequency bands by applying bandpass filter. I am trying to use filterbank. Shouldn't I be multiplying the filterbank with the input signal to get that done? I understand this is something off topic. But, any help would be very helpful.

**Comment by russellb23** [comment]
Thank you piem. This is indeed what I was looking for. I am trying to understand what does this line do:
>new_samples = pvs_out[n].rdo(band_grain)

As far my understanding goes, pvs_out is a list of phase vocoder objects of length = n_filters and `rdo` method computes the inverse transform of the spectral value generate the signal. 

band_grain gives me values like, `[0.         0.01359085 0.         ... 0.         0.         0.        ]` for norm and `[ 3.1415927e+00  3.1415925e+00 -2.1368411e+00 ...  1.6687086e+00
 -1.0298658e-03  0.0000000e+00]` for phase. But upon inverse fft, I get only "0." in all the chunks. Any idea what could be wrong?

**Comment by piem** [comment]
Your understanding is correct, except `pvoc.rdo` does a bit more than just the inverse fft, as it computes the full signal re-synthesis using overlap-add (see `src/spectral/phasevoc.{h,c}` for references and implementation details).

The reason you find very small numbers (displayed as `0.`) is that there is very little energy in each of these bands, so the amplitude of the reconstructed signals is very small. This is why a gain should be applied (before writing the the file to avoid dithering).

And yes, [zero has a sign](https://en.wikipedia.org/wiki/Signed_zero).

**Comment by piem** [comment]
hi @russellb23 

i'm closing this issue now, let us know if you have more questions!

best, piem
