### ISSUE TITLE
Port to ffmpeg 4.0

### ISSUE THREAD

**Issue by dvzrv** [aubio/aubio#174]
Arch Linux will soon move to ffmpeg 4.0, which requires me to rebuild aubio against that version.
The build fails, though: 
[aubio_build_log.txt](https://github.com/aubio/aubio/files/1944218/aubio_build_log.txt)

**Comment by piem** [comment]
hi @dvzrv , did you see 967e404 ?

**Comment by dvzrv** [comment]
@piem sorry, just now. Shouldn't build software when tired ;-)
Will close as soon as the build is successful!

**Comment by dvzrv** [comment]
Thanks a lot, this worked!

**Comment by piem** [comment]
np, thanks for testing! i guess a release is due already! :)
