### ISSUE TITLE
Error installing Aubio through pip

### ISSUE THREAD

**Issue by hunaa** [aubio/aubio#177]
I am using the command: **pip install aubio** on Python 3.6.0 and this is the error I am getting,

Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Hamid\\AppData\\Local\\Temp\\pip-install 21wxrqe1\\aubio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n
', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Us
ers\Hamid\AppData\Local\Temp\pip-record-qjracyfs\install-record.txt --single-ver
sion-externally-managed --compile" failed with error code 1 in C:\Users\Hamid\Ap
pData\Local\Temp\pip-install-21wxrqe1\aubio\

**Comment by piem** [comment]
hi @hunaa 

Could you try with latest `HEAD` to see if it helps?

    pip install -v git+https://github.com/aubio/aubio.git

A few more lines before and after this one could be helpful to understand what failed too.

**Comment by hunaa** [comment]
Tried and found this,
![image](https://user-images.githubusercontent.com/20323069/40233141-455d987e-5abb-11e8-9254-0f887c038822.png)

**Comment by piem** [comment]
The messages include a link to landinghub.visualstudio.com/visual-cpp-build-tools, probably because no compiler can be found.

Since you're using conda, try installing the pre-compiled binary:

    conda install -c conda-forge aubio
