### ISSUE TITLE
improve aubionotes' performance

### ISSUE THREAD

**Issue by alexreg** [aubio/aubio#18]
aubionotes currently works very poorly, even on very simple monophonic melodies. Are you aware of some settings that make it work decently, by chance?

**Comment by piem** [comment]
hi @alexreg 

a new option has been added to aubionotes:

```
  -M, --minioi value  Set the minimum inter-onset interval, in seconds, the
  shortest interval between two consecutive notes. Defaults to 0.030
```

this might help you getting more accurate results.

best, piem
