### ISSUE TITLE
problem submitting app to TestFlight

### ISSUE THREAD

**Issue by simonator123** [aubio/aubio#181]
I ran into an issue when submitting my app to TestFlight. I submitted the app from within Xcode 9, and when I did, I got an error saying:

"Invalid Bundle Structure. The binary file Frameworks/aubio.framework/aubio is not permitted. Your app can't contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. 

I'm using the Aubio 0.4.4 framework.

**Comment by theronic** [comment]
Maybe try [this solution](https://stackoverflow.com/a/29859063/198927)?

**Comment by simonator123** [comment]
Ok, great. It looks like that fixed it, thank you!
