### ISSUE TITLE
[raspberrypi] running aubio tools with jack [was: jack errors]

### ISSUE THREAD

**Issue by Wqrld** [aubio/aubio#185]
When trying to run aubiopitch im getting:

```
pi@raspberry:~/aubio $ aubiopitch
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
jackd 0.124.1
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details

connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
connect(2) call to /tmp/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
AUBIO ERROR: jack server not running?

```
running a raspberry pi. Is it possible to work without jack? And otherwise how do i get jack to work/check if it is running? I am not sure how to run jack right as it seems to do nothing.
```
pi@raspberry:~/aubio $ sudo jackd -R -d alsa
jackd 0.124.1
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
(ends)
```

pi 3b newest raspbian and aubio just installed today. (had some problems installing but it worked after a combination of apt-get and building from git)

**Comment by Wqrld** [comment]
the python lib works just fine with the alsa demo, cli tools are still broken.

**Comment by flappix** [comment]
Your command for launching jack looks right. It's normal that it's doing nothing cause it's a server.
Just start jack like you did then open another terminal and launch aubio. Or add a & behind the jack command if you want to launch both commands in the same terminal.

**Comment by Wqrld** [comment]
Is jack supposed to exit after running the start command?

**Comment by piem** [comment]
hi @Wqrld, hi @flappix 

yay, aubio on raspberry pi! :)

> Is it possible to work without jack?

sure, if you pass a file name to aubio's command line tools, you should be able to analyze those files. try `aubiopitch soundfile.wav`. also see `aubiopitch -h`.

if you mean _use aubio command line tools in real time without jack_, no it's not possible at the moment.

> And otherwise how do i get jack to work/check if it is running?

you seem to be using `sudo` for jack, but not for `aubiopitch`. you should be able to run everything in user space.

> Is jack supposed to exit after running the start command?

on my machine (debian stable), jackd will exit if started by aubio command line tools, but your mileage may vary.

let us know if that answers your questions!

best, piem

**Comment by piem** [comment]
hi @Wqrld, any feedback on this?

cheers, piem

**Comment by Wqrld** [comment]
Seemed to have missed this message, trying it soon

**Comment by piem** [comment]
hi @Wqrld 

have you had a chance to try running `aubiopitch -j` without launching `jackd` as root first ?

cheers, piem

**Comment by Wqrld** [comment]
i seem to have broken aubio while trying some things so now im getting:
`aubiopitch: error while loading shared libraries: libaubio.so.5: cannot open shared object file: No such file or directory` Ill try to uninstall aubio but im not sure where i got this error from.

**Comment by piem** [comment]
hi @Wqrld 

This seems to be a problem with your installation. Did you figure it out?

Please re-open if you think there is anything that should be fixed in aubio,

cheers, piem
