### ISSUE TITLE
Pitch extraction works with only single audio file

### ISSUE THREAD

**Issue by hunaa** [aubio/aubio#186]
Hello, 

I am using the code provided for pitch tracking in the demo folder.

Using this, I am able to extract the pitch feature vector for a single file however while looping through the entire directory of audio files I am getting the error,

![image](https://user-images.githubusercontent.com/20323069/42838924-80876c4c-8a1b-11e8-98cd-1ecc7c73f795.png)

Here's the link to my code, 
https://pastebin.com/739f3MLA

kindly help me understand and resolve this error.

**Comment by piem** [comment]
hi @hunaa 

it looks like you are overwritting `aubio.pitch` at line 44.

let us know if you have other issues.

best, piem
