### ISSUE TITLE
SnareTools in the App Store!

### ISSUE THREAD

**Issue by simonator123** [aubio/aubio#190]
Sorry, I looked for a way to message @piem personally on here, but couldn't find a way. 

My app, SnareTools, uses aubio to determine how accurately a user is playing along to manually entered or random rhythms. It is currently in the Apple app store as of a couple days ago. Thanks for aubio. I wouldn't have been able to do what I wanted without it!

Jared

**Comment by piem** [comment]
hi @simonator123, great news! you can contact us via https://aubio.org/contact
