### ISSUE TITLE
aubionotes not working when built from source

### ISSUE THREAD

**Issue by Rippert** [aubio/aubio#196]
I tried building version 4.6 of Aubio and Aubio-tools. When I try to run:

`aubionotes -j`

I get this error:

`aubionotes: symbol lookup error: aubionotes: undefined symbol: aubio_log`

I actually get this error whenever I try to invoke aubionotes with or without any options.

This is on Rasberian, and the older version, 0.4.3, installed from the repo works.

**Comment by Rippert** [comment]
The fix above did not survive a log-out log-in cycle.

I checked /usr/local/lib and these files are present:

`/usr/local/lib/libaubio.so.5.3.7`
`/usr/local/lib/libaubio.so -> libaubio.so.5.3.7`
`/usr/local/lib/libaubio.so.5 -> libaubio.so.5.3.7`

I tried a `sudo ldconfig` but no luck.

`export LD_LIBRARY_PATH=/usr/local/lib` works, but seems like there's something broken if I have to do that.

**Comment by piem** [comment]
hi @Rippert 

Could it be that there is an older version of libaubio installed on your system?

You should be able to find out by running `ldd ./aubionotes` (before setting `LD_LIBRARY_PATH`).

If that's the case, you could either:

 - keep using 0.4.6 in use space by setting `LD_LIBRARY_PATH` (using `source ./scripts/setenv_local.sh` for instance)
 - or remove the older version before re-installing the latest one

let us know how it goes!

best, piem

**Comment by Rippert** [comment]
@piem 

You are correct. After I remove` libaubio5` via `sudo apt-get remove libaubio5` and run `sudo ldconfig`, I can see the library change to the correct one using your suggested `ldd` command. It then works correctly. The `ldconfig` fixed it, no need to reinstall.

Thank You.
