### ISSUE TITLE
document how to build aubio in a virtualenv

### ISSUE THREAD

**Issue by stuaxo** [aubio/aubio#2]
Is there a way to install aubio in virtualenv ?

Pretty much everyone uses virtualenv now .. but not really sure how to install the python libraries from the source so I can try and run it in one.

**Comment by piem** [comment]
Hi @stuaxo ,

I've modified `setup.py` so that this should work:

    pip install -r https://raw.githubusercontent.com/aubio/aubio/develop/requirements.txt
    pip install git+https://github.com/aubio/aubio.git@develop

Does this work for you?

Thanks, Paul

**Comment by piem** [comment]
Should be even simpler now (after @5f6324e):

    pip install git+https://github.com/aubio/aubio.git@develop
