### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by niugx** [aubio/aubio#213]
Hi ,

i am guoxiang niu, we sent the security issue which i found to contact@aubio.org mailbox failed yesterday, it seems your mail server connection time out.

as it may be a potential vulnerability, i feel it is better i send the issue to you mailbox before identify it as a vulnerability, so, in order to send the issue successfully, would you like to show me another mailbox ?

thanks.
guoxiang niu

**Comment by piem** [comment]
hi @niugx 

I replied to your email, but it seems the message may have been marked as spam on your side.

Could you try again sending us a report, maybe from another email server or via https://aubio.org/contact? You can also post a link to a file encrypted with [my gpg key](https://piem.org/piem.gpg).

best, piem

**Comment by niugx** [comment]
i received you mail yesterday，but when i reply you，it failed.

**Comment by niugx** [comment]
i received you mail yesterday，but when i reply you，it failed.

**Comment by piem** [comment]
You can also contact me (piem) on irc (freenode) and gitter.
