### ISSUE TITLE
Can't install 0.4.8 with Conda on Windows

### ISSUE THREAD

**Issue by ahodges9** [aubio/aubio#215]
I am having some issues getting 0.4.8 pulled down from conda-forge on windows. Conda only seems to want to pull down 0.4.6. Looking at conda-forge 0.4.6 is the latest supported for win32, but for win74 it claims to support 0.4.8. I don't see 0.4.8 in the channel: https://conda.anaconda.org/conda-forge/win-64/ so is there some configuration messed up?

I was able to force it by installing the file directly, but this isn't ideal

**Comment by ahodges9** [comment]
And it seems to be working now... Must have just been some conda infrastructure issue. Its not in the channel and properly being picked up

**Comment by piem** [comment]
Glad to know it works. The files are here: https://anaconda.org/conda-forge/aubio/files

To install aubio through conda:

    conda install -c conda-forge aubio

There was an issue with the previous build (conda-forge/aubio-feedstock#15), but `0.4.8-py36h7fad82b_1` was released about 5 days ago and should be ok.
