### ISSUE TITLE
[Q] copy from multiple ogg sources to sink without decoding

### ISSUE THREAD

**Issue by eadmaster** [aubio/aubio#220]
is it possible to append from multiple ogg file sources to a single ogg sink file?

**Comment by piem** [comment]
hi @eadmaster,

If you have `sox` installed, it should be as easy as:

    sox file1.ogg file2.ogg file3.ogg longfile.ogg

In aubio, there is no support to write ogg files (yet), but you could create a short python script or C program that reads multiple ogg files and write them into a wav file, then convert this file to ogg, for instance with `oggenc`.

best, piem

**Comment by eadmaster** [comment]
thank you for the `sox` tip, i'll give it a try!
