### ISSUE TITLE
fundamental frequency

### ISSUE THREAD

**Issue by SarahTeoh** [aubio/aubio#223]
I am using audiopitch to detect the fundamental frequency of an audio stream from microphone.
However, I always got values that are much more greater than the normal fundamental frequency range of human voice,eg: 1000+ Hz or 3000+ Hz. Below are my settings:
`BUFFER_SIZE           = 2048
CHANNELS                = 1
FORMAT                  = pyaudio.paFloat32
METHOD                  = "default"
SAMPLE_RATE             = 44100
HOP_SIZE                = BUFFER_SIZE//2
PERIOD_SIZE_IN_FRAME    = HOP_SIZE`  

Is there any problem with my settings? or should i use band pass filter? if yes, can I do this using aubio?

**Comment by piem** [comment]
hi @SarahTeoh 

If all results incorrect, there is most likely something wrong. Have you tried `python/demos/demo_pyaudio.py`? 

Also, singing voice can go as low as 100Hz, so you may want to increase the window size to 4096.

best, piem

**Comment by piem** [comment]
hi @SarahTeoh 

please provide more info if you are still having issues.

best, piem
