### ISSUE TITLE
Is it possible to use libblas or OpenBLAS in macOS?

### ISSUE THREAD

**Issue by Lord-Kamina** [aubio/aubio#225]
I know the docs say they should be implemented via Accelerate framework but I'm working on a cross-platform app and ideally I want to make dependencies as uniform as possible across different OS.

Supposing I have installed the appropriate BLAS libraries, would it work as expected?

**Comment by Lord-Kamina** [comment]
What I want to know is, are there any checks for Darwin that might override whatever package pkg-config says and try to shove Accelerate down my throat?

**Comment by piem** [comment]
Quite. The code in `aubio_priv.h#77` includes accelerate first. You try this patch and see if it helps.

best, piem

```patch
diff --git a/src/aubio_priv.h b/src/aubio_priv.h
index ab6afb28..620107af 100644
--- a/src/aubio_priv.h
+++ b/src/aubio_priv.h
@@ -74,12 +74,8 @@
 #include <stdarg.h>
 #endif
 
-#if defined(HAVE_ACCELERATE)
-#define HAVE_ATLAS 1
-#define HAVE_BLAS 1
-#include <Accelerate/Accelerate.h>
-#elif defined(HAVE_ATLAS_CBLAS_H)
-#elif defined(HAVE_BLAS)
+#if defined(HAVE_BLAS) // --enable-blas=true
+// check which cblas header we found
 #if defined(HAVE_ATLAS_CBLAS_H)
 #define HAVE_ATLAS 1
 #include <atlas/cblas.h>
@@ -87,7 +83,16 @@
 #include <openblas/cblas.h>
 #elif defined(HAVE_CBLAS_H)
 #include <cblas.h>
+#elif !defined(HAVE_ACCELERATE)
+#error "HAVE_BLAS was defined, but no blas header was found"
+#endif /* end of cblas includes */
 #endif
+
+#if defined(HAVE_ACCELERATE)
+// include accelerate framework after blas
+#define HAVE_ATLAS 1
+#define HAVE_BLAS 1
+#include <Accelerate/Accelerate.h>
 #endif
 
 #ifdef HAVE_ACCELERATE```

**Comment by piem** [comment]
hi @Lord-Kamina 

I recently pushed 2ca09bf in master, which helps building against different blas implementations on linux, but didn't check compiling against a custom blas on osx. Does it work for you?

cheers, piem

**Comment by piem** [comment]
Ok, thank you for your report!

cheers, piem
