### ISSUE TITLE
Tempo tracking: Am I doing this right?

### ISSUE THREAD

**Issue by Lord-Kamina** [aubio/aubio#226]
I'm working on a game, currently we have a pretty broken algorithm  for flashing a song's cover in time with the beat. I decided to try implementing something better with aubio. We're already using ffmpeg for processing everything and we store currently playing tracks in boost circularbuffers.

I thought a convenient way to do this might be to piggy-back on our audio preloading code (and also trying to use samples already in memory so I also went looking at #127) , something like this:

```c++
fvec_t* AudioBuffer::makePreviewBuffer() {
	{
		std::unique_lock<mutex> l(m_mutex);
		ScreenSongs::previewSamplesBuffer.reset(new_fvec(m_data.size() / 2),del_fvec);
		ScreenSongs::previewSamplesBuffer->length = m_data.size() / 2;
			std::clog << "audio/debug: m_data.size(): " << m_data.size() << std::endl;
		for (size_t rpos = 0, bpos = 0; rpos < m_data.size(); rpos += 2, bpos ++) {
			std::clog << "audio/debug: bpos: " << bpos << ", rpos: " << rpos << ", m_pos: " << m_pos << std::endl;
			float temp = ((da::conv_from_s16(m_data[rpos]) + da::conv_from_s16(m_data[rpos + 1])) / 2);
			ScreenSongs::previewSamplesBuffer->data[bpos] = temp;
		}
	}
	m_cond.notify_one();
	return ScreenSongs::previewSamplesBuffer.get();
};

// (this is only the relevant part of the preloading function)
if (mpeg.audioQueue.prepare(m_pos)) {
	if (kv.first == "background" && m_preview && m_pos > 0) {
		int hop_size = 1024;
		int win_size = 2048;
		fvec_t* previewSamples = mpeg.audioQueue.makePreviewBuffer();
		fvec_t* previewBeats = ScreenSongs::previewBeatsBuffer.get();
		intptr_t readptr = 0;
		fvec_t tempoSamplePtr = *new_fvec(hop_size);
		aubio_tempo_t* tempo = new_aubio_tempo("default", win_size, hop_size, Audio::getSR());
			std::clog << "audio/debug: previewSamples.length: " << previewSamples->length << ", previewBeats->length: " << previewBeats->length << std::endl;
		while (readptr < previewSamples->length) {
			std::clog << "audio/debug: readptr: " << readptr << std::endl;
			tempoSamplePtr.data = &previewSamples->data[readptr];
			aubio_tempo_do(tempo,&tempoSamplePtr,previewBeats);
			if (previewBeats->data[0] != 0) {
				std::clog << "aubio/debug: beat at: " << aubio_tempo_get_last_ms(tempo) << "ms (" << aubio_tempo_get_last_s(tempo) << "s). frame: " <<  aubio_tempo_get_last(tempo) << ", BPM: " << aubio_tempo_get_bpm(tempo) << ", confidence: " << aubio_tempo_get_confidence(tempo) << std::endl;
			}
			readptr += hop_size;
		}
	}	
continue;  // Buffering done
}
```

Currently it *appears* to work, or at least it's detecting *something* (although the confidence is almost always 0 or something like 0.00043 or whatever)

Does this look about right to you? 
Things I'm unsure about: 
 ~~* Whether our samples at this point in the code are actually mono or not.~~ They weren't, so I mixed them down (hopefully I did it right)
 * Can I use non-power-of-two window and hop-sizes if I'm using fftw3f?
 * How can I increase confidence? Do I need bigger hops/windows? smaller? is this actually relevant?
 * Can I store all the detected beats on a container for later reference, instead of what I'm doing?

Edit: Updated code, previous version had inverted a couple variables causing a segfault occasionally.

**Comment by piem** [comment]
hi @Lord-Kamina 

1. you can use non-power of two hop size regardless of the fft implementation. only fftw3 supports non-power-of-two window sizes, and power-of-two sizes should be preferred as much as possible.
2. the confidence of the beat tracker only indicates the salience of the selected peak; it is experimental and should not be trusted as a confidence measure.
3. you can store the timestamps in an fvec_t (or whatever type of vector you like), but you will have to decide first how large its buffer should be (or reallocate it every so often to grow as required).

hth, best,
piem
