### ISSUE TITLE
Resizing an fvec_t

### ISSUE THREAD

**Issue by Lord-Kamina** [aubio/aubio#230]
Is it at all recommended to do this? I've seen examples of code that just changes the "length" value for an `fvec_t` but AFAICT, without really resizing the array, that could only result in aubio trying to use memory containing something else?

**Comment by piem** [comment]
hi @Lord-Kamina 

Yes, `fvec_t` is one of the few structures (that is one declared in the `.h` not the `.c`), so you can create it on the stack quickly and fill it with whichever values suits you.

Here is an example of creating an `fvec_t` on the stack and pointing its member to the second half of the second row of a matrix:

```c
  fmat_t *m = new_fmat(2, 16); // allocate a new matrix                          
  fvect_t v;                   // created on the stack                           
  v.length = 8;                // set its length                                 
  v.data = m->data[1] + 8;     // point to start of data                         
  // &v is now ready to use as any other vector                                  
  fvec_ones(&v);               // fill our 'vector'                              
  fmat_print(m);               // the content of m has changed               
  // clean-up                                                                    
  del_fmat(m);                 // nothing else to delete 
```

Of course you will want to make sure read/write out-of-bounds accesses and double free are prevented when writing this kind of code.

Let us know if this answers your question!

cheers, piem

**Comment by Lord-Kamina** [comment]
>hi @Lord-Kamina  ...

@piem thanks, but not really.

What I want to know is if for example doing something like:

```c++
fvec_t* vec = new_fvec(4);
vec->length = 8;
vec[5] = 1.0;
```

Is safe to do?
From what I saw of the implementation, I would assume not; but I'd like to be sure. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by piem** [comment]
hi @Lord-Kamina 

No, that program should fail, since `vec` was allocated with a memory large enough to fit only 4 elements, no more. You could shrink a vector instead of trying to make it larger, but calling `del_fvec(vec)` would then cause a memory leak, unless the `length` member is set back to the original value.

You are probably best to allocate all the memory required for your program at start time, then use the [example provided above](https://github.com/aubio/aubio/issues/230#issuecomment-456434714).

cheers, piem

**Comment by piem** [comment]
Hi @Lord-Kamina 

Closing this issue now, I hope it answered your questions.

best, piem
