### ISSUE TITLE
PermissionError(13, 'Access is denied') while updating my numpy

### ISSUE THREAD

**Issue by vanshmohale** [aubio/aubio#234]
I am trying to update my numpy and this is the error I received. I found a similar thread to this error but that wasn't able to remove it so I created a new one.
_______________________________________________________________________
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::numpy-1.15.1-py37ha559c80_0'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')
______________________________________________________________________

**Comment by piem** [comment]
hi @vanshmohale 

this is a duplicate of #218. The problem seems to be in conda itself, which fails uninstalling packages on windows while upgrading. @conda-forge any thoughts on this ? 

cheers, piem

**Comment by vanshmohale** [comment]
yes it is the same issue. I am using anaconda3 version- 5.3.1 and python- 3.7.0
So what am I expected to do if the problem is with my conda?

**Comment by vanshmohale** [comment]
Hey the error is resolved.  I am not exactly sure what the problem was but what I did was, I tried installing it using pip.

After writing this command, I received,
>>>pip install numpy==1.16.1

__________________________________________
 Found existing installation: numpy 1.15.1
    Uninstalling numpy-1.15.1:
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\add_newdocs.py'
Consider using the `--user` option or check the permissions.
__________________________________________


then as asked by it, I tried,
>>>pip install --user numpy==1.16.1

____________________________________________
 The script f2py.exe is installed in 'C:\Users\765349\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.16.1
____________________________________________


and numpy was updated.
Thankyou for your help though @piem
