### ISSUE TITLE
timing issue in demo_wav2midi.py

### ISSUE THREAD

**Issue by chaoxinzheng** [aubio/aubio#240]
I don't think the below time is correct. I use this to convert a wave file generated from midi. The below is generating weird outcome. When i replace time=0 with time=delta, it works perfectly.

        if new_note[2] > 0:
            track.append(Message('note_off', note=int(new_note[2]),
                velocity=127, time=0)
                )

**Comment by piem** [comment]
hi @chaoxinzheng 

good catch, this should be fixed with f55630c5.

cheers, piem
