### ISSUE TITLE
new_fmat performance

### ISSUE THREAD

**Issue by dSalazar10** [aubio/aubio#242]
The function "new_fmat", found on line 24 in "fmat.c", is used to create a fmat_t object. I noticed that there is a second loop to set all values to zero:

[code]
for(j = 0; j < s->length; ++j)
{
  s->data[i][j]=0.;
}
[code]

I looked up calloc and it initialized all values to zero by default. Correct me if I am wrong, but couldn't this loop can be removed?

http://www.cplusplus.com/reference/cstdlib/calloc/
https://github.com/aubio/aubio/blob/master/src/fmat.c

**Comment by piem** [comment]
hi @dSalazar10 

good point! I believe this is solved in the neural network branches, which should be published here soon.

thanks, piem

**Comment by techtravel7** [comment]
Thank you for answering my question @piem.

**Comment by dSalazar10** [comment]
Thank you for answering my question @piem
