### ISSUE TITLE
iOS Spectrogram example

### ISSUE THREAD

**Issue by aleksandrshoshiashvili** [aubio/aubio#251]
Hi,

first of all: thank you for this library!

I trying to use Aubio in iOS project, mainly for spectrogram creation. I have no idea how to do it. Maybe someone has a sample code on Swift how to do it?

Thanks in advance!

**Comment by piem** [comment]
hi @aleksandrshoshiashvili 

thank you for the feedback. I guess you are looking for a way to draw norm vectors of the phase vocoder as a spectrogram, or a waterfall like graph.

`aubio_pvoc_t` will compute this vector for you, but you will have to find out how to accumulate them and draw them in you favorite application.

you might want to look at `demo_stpectrogram.py` in the `python/demos` folder for inspiration.

let us know if that helps,

best, piem
