### ISSUE TITLE
How to get duration with aubio.notes?

### ISSUE THREAD

**Issue by Ellegarden1219** [aubio/aubio#254]
Hello,

I am trying to get sounds duration with each pitch.
I am using pyaudio and trying to make it midi note, and by using aubio.pitch, I could extract pitch, but I believe that I need to use aubio.notes to get duration.  

I know there is some documents, but I could not really figure out, so it would be great if you can give me some tips.

**Comment by piem** [comment]
hi @Ellegarden1219 

apologies for the late reply. Have a look at `aubio`, the command line tool installed with the python module. `aubio notes -h` will let you know more about the options.

best, piem

**Comment by benjmcarr** [comment]
Hi @piem,

First, thanks for the great library. 

But I'm also struggling with note duration and the documentation isn't clear to me. `aubio notes` gives [start vel last] values, presumably 'vel' is velocity, 'start' and 'end' are midi pitches, but how do I retrieve duration?

**Comment by benjmcarr** [comment]
Think I've got it now, 'start' is the start of a note and 'last' is the end of a note. Duration is just the difference. This wasn't clear to me at first since I was filtering out any notes with start=0, as done in the notes demo. These notes need to be included to get proper durations.
