### ISSUE TITLE
Cant set prefix in waf install

### ISSUE THREAD

**Issue by autoantwort** [aubio/aubio#260]
I tried many different combinations in the command line, but I cant change the prefix while installing. The command is `./waf install "--prefix=" --destdir "$PWD/../src/lib/aubio"`. But the files gets installed something like this: `C:\Users\My Name\Lichtsteuerung.git\src\lib\aubio\users\leande~1\appdata\local\temp\lib\libaubio-5.dll (from build\src\libaubio-5.dll)`  
`waf --help` say that the default prefix is `'C:\\users\\leande~1\\appdata\\local\\temp'`

**Comment by piem** [comment]
hi @autoantwort,

- `--prefix` requires an argument, and must be passed to the configure phase 
- `--destdir` is the location where the files will be copied, useful to create a tarball without actually writing files in the final location

example:
```
$ ./waf configure --prefix /opt
$ ./waf build
$ ./waf install --destdir /tmp/dist-aubio
$ ls /tmp/dist-aubio/opt/lib
libaubio.a  libaubio.so  libaubio.so.5  libaubio.so.5.4.8  pkgconfig
```

let us know if this helps,
cheers, piem

**Comment by autoantwort** [comment]
Hi @piem, 
yes it helped. That part was not very clear in the `./waf --help` output, especially for which command a parameter is. Maybe you should mention that`--prefix` is for `configure` and `--destdir` for `install`.
