### ISSUE TITLE
documentation example: lines shifted

### ISSUE THREAD

**Issue by cipo7741** [aubio/aubio#267]
Dear aubio-devs,

the code-sample in https://aubio.org/manual/latest/develop.html#reading-a-sound-file
is shifted.

I guess `../tests/src/io/test-source.c` changed.

Anyway, thanks for aubio.

**Comment by piem** [comment]
thanks for your report @cipo7741, this should be fixed now (see this [recent rebuild](https://aubio.readthedocs.io/en/latest/develop.html#reading-a-sound-file) for an example).

the updated documentation will be pushed on the server shortly.

let us know if you see anything else!

cheers, piem
