### ISSUE TITLE
Acoustic Piano → Midi

### ISSUE THREAD

**Issue by ccorcos** [aubio/aubio#271]
I'm looking for a "simple" piece of software that can listen to audio from the microphone on my computer and convert that to midi notes as a virtual audio input. Looks like this library might not support multi-note detection like this but I thought I'd ask. If not, are there any other tools out there you can recommend?

Thanks

**Comment by piem** [comment]
hello @ccorcos 

for now aubio does only monophonic pitch tracking. it will likely be possible to do polyphonic tracking at some point, but no precise roadmap yet.

cheers, Paul

**Comment by ccorcos** [comment]
Cool. Thanks!
