### ISSUE TITLE
Aubio Track

### ISSUE THREAD

**Issue by hehehehehhe** [aubio/aubio#287]
Does anyone know how to get aubiotrack to work with python on a MacBook?

**Comment by piem** [comment]
hi @hehehehehhe 

see `aubio` command line tool, in particular `aubio beat` and `aubio tempo`

https://aubio.org/manual/latest/cli.html#aubio

see also `python/demos/demo_tempo.py` for a code example.

best, piem

**Comment by hehehehehhe** [comment]
hi! i am already using aubio tempo to get the beats per minute of a song, but I am trying to find the time stamp of each beat. Reading through the aubio manual it looked like I am supposed to use aubiotrack in order to get this but I am not getting this to work.

**Comment by hehehehehhe** [comment]
> hi @hehehehehhe
> 
> see `aubio` command line tool, in particular `aubio beat` and `aubio tempo`
> 
> https://aubio.org/manual/latest/cli.html#aubio
> 
> see also `python/demos/demo_tempo.py` for a code example.
> 
> best, piem

hi! i am already using aubio tempo to get the beats per minute of a song, but I am trying to find the time stamp of each beat. Reading through the aubio manual it looked like I am supposed to use aubiotrack in order to get this but I am not getting this to work.

**Comment by piem** [comment]
hi @hehehehehhe 

as mentionned in my previous message, you can use `aubio beat /path/to/audiofile` for that.

please close this issue if that answers your question,

best, piem

**Comment by hehehehehhe** [comment]
> hi @hehehehehhe
> 
> as mentionned in my previous message, you can use `aubio beat /path/to/audiofile` for that.
> 
> please close this issue if that answers your question,
> 
> best, piem

Sorry, I am new to aubio and I'm having trouble figuring out how to use that command in Python. I am trying to use this command in my Python project and I am not sure where to use this command. For tempo and such, I had "from aubio import tempo" at the top but this doesn't seem to work for aubio beat.

**Comment by piem** [comment]
@hehehehehhe `aubio` is also the name of the command line tool, available from the command line (Terminal) in the environment where the `aubio` python module was installed.

good luck, piem

**Comment by hehehehehhe** [comment]
> @hehehehehhe `aubio` is also the name of the command line tool, available from the command line (Terminal) in the environment where the `aubio` python module was installed.
> 
> good luck, piem

Do you know by any chance a function in the aubio python module where I could figure out the time stamp of beats rather than using the command line tool? Any help would be appreciated. Thanks so much!

**Comment by piem** [comment]
@hehehehehhe 

yes, as mentionned earlier, `python/demos/demo_tempo.py` does exactly this.

good luck, piem

**Comment by hehehehehhe** [comment]
> @hehehehehhe
> 
> yes, as mentionned earlier, `python/demos/demo_tempo.py` does exactly this.
> 
> good luck, piem

Thank you so much I think this is almost it! For some reason it is not returning the same amount of beats as the number of total beats though. I am getting 452 total beats but this function is only returning the time of 437 values, do you know why this could be happening? Thanks so much!

**Comment by piem** [comment]
@hehehehehhe 

i assume you are getting 437 beats with the script `demo_tempo.py`.

now, how are you getting 452 beats? manually?

best, piem

**Comment by hehehehehhe** [comment]
> @hehehehehhe
> 
> i assume you are getting 437 beats with the script `demo_tempo.py`.
> 
> now, how are you getting 452 beats? manually?
> 
> best, piem

Yes, I am getting 437 beats when I use demo_tempo.py. I am getting 452 beats when I used the tempo() function to calculate the bpm of each beat.

**Comment by hehehehehhe** [comment]
I think it's not getting the time stamps of the first few beats because the first value is 1.7 seconds but the first beat should be earlier.

**Comment by piem** [comment]
@hehehehehhe right, as you probably understood already, the results are not perfect, and this is where the name _aubio_ comes from.

best, piem

**Comment by hehehehehhe** [comment]
> @hehehehehhe right, as you probably understood already, the results are not perfect, and this is where the name _aubio_ comes from.
> 
> best, piem

Yeah that makes sense, thanks! Do you know if there's any difference between the method in demo_tempo.py or using .get_last_s() of a tempo object to get the time stamps of each beat? They are both returning different time stamps but I am not sure what the difference is between these two methods. Thank you so much for your help!

**Comment by piem** [comment]
The `get_last_s` can be used to get the previous timestamp *after* `aubio.tempo.__call__` emitted it.

Probably not something you need at this time.

best, piem

**Comment by hehehehehhe** [comment]
> The `get_last_s` can be used to get the previous timestamp _after_ `aubio.tempo.__call__` emitted it.
> 
> Probably not something you need at this time.
> 
> best, piem

Thank you so much, I really appreciate your help!!!

**Comment by hehehehehhe** [comment]
Also, I was able to get the same number of total beats by increasing the win size of the tempo object!
