### ISSUE TITLE
aubionotes: undefined symbol: aubio_notes_set_release_drop

### ISSUE THREAD

**Issue by ct2034** [aubio/aubio#289]
I built the latest verison eadb7f61c8851bdc2438e9f3c7e321d700d9fe50.
With all libraries configured.

When I run `aubionotes`, I get:
`aubionotes: symbol lookup error: aubionotes: undefined symbol: aubio_notes_set_release_drop`

**Comment by piem** [comment]
hi @ct2034 

it seems you have an older version of aubio installed on your system. could you try uninstalling that old version first?

otherwise, setting `LD_LIBRARY_PATH` to where the latest `libaubio.so` is installed should be enough.

let us know if that helps,
thx, piem

**Comment by ct2034** [comment]
@piem Thanks for the answer. 

I have uninstalled everything using `./waf uninstall`, cleaned, rebuilt, installed again but still the same error.
Where will the `libaubio.so` be installed by `./waf install`?

For your info: I have had previously also installed aubio via pip. But I uninstalled that one, before building from source and as far as I can tell, nothing is left from that installation.

Note: The message is gone and everything working when commenting out the one function call, as I have done here: https://github.com/ct2034/aubio/tree/fix_undefined_symbol

**Comment by piem** [comment]
@ct2034 

by default, `libaubio.so` is installed in `/usr/local/lib`

what do you get when running the following command?

    ldd `which aubionotes`

i suspect you have an older libaubio installed in `/usr/lib`:

    find /usr/lib -iname libaubio.so -ls

best, piem
