### ISSUE TITLE
Error after run make

### ISSUE THREAD

**Issue by TanZng** [aubio/aubio#299]
make [1]: the directory '/ home / tanx / aubio' is entered
./scripts/get_waf.sh
/tmp/tmp.OYuu9XdftJ ~ / aubio
gpg: key 49B4C67C05277AAA: "Thomas Nagy <tnagy@waf.io>" unchanged
gpg: Total quantity processed: 1
gpg: unchanged: 1
gpg: assuming signed data is in 'waf-2.0.17.tar.bz2'
gpg: Signed on Sun 02 Jun 2019 03:09:41 CDT
gpg: using RSA key 8AF22DE5A06822E3474F3C7049B4C67C05277AAA
gpg: Correct signature of "Thomas Nagy <tnagy@waf.io>" [unknown]
gpg: ATTENTION: This key is not certified by a trusted firm!
gpg: There is no indication that the signature belongs to the owner.
Primary key fingerprints: 8AF2 2DE5 A068 22E3 474F 3C70 49B4 C67C 0527 7AAA
/tmp/tmp.OYuu9XdftJ/waf-2.0.17 /tmp/tmp.OYuu9XdftJ ~ / aubio
./scripts/get_waf.sh: line 42: python: command not found
make [1]: *** [Makefile: 53: getwaf] Error 127
make [1]: exit directory '/ home / tanx / aubio'
make: *** [Makefile: 50: checkwaf] Error 2

**Comment by piem** [comment]
hello @TanZng 

    ./scripts/get_waf.sh: line 42: python: command not found

you will need to have python installed to build aubio.

if you are running into more troubles, please let us know more details about your operating system and environment.

also, please consider [installing pre-built binaries](https://aubio.org/manual/latest/installing.html#pre-compiled-binaries) if compiling is an issue.

cheers, piem

**Comment by TanZng** [comment]
My OS is Ubuntu 20.04 but python runs with "python3" command instead of "python"

**Comment by TanZng** [comment]
My OS is Ubuntu 20.04 but Python runs with "python3" command instead of "python"

**Comment by piem** [comment]
You could either install `python-is-python3`, or modify the script.

If you need more interactive help, please hop on irc or gitter.

cheers, piem
