### ISSUE TITLE
dyld: Library not loaded 

### ISSUE THREAD

**Issue by adamski** [aubio/aubio#30]
I’ve been trying to debug a crash on launch on device (iOS) which seems to be coming from aubio:

```
dyld: Library not loaded: /usr/local/lib/libaubio.4.dylib
  Referenced from: /var/mobile/Applications/CCFF68BA-4186-421E-A07E-D5482B654D98/MyApp.app/MyApp
  Reason: image not found
```

This has been happening since I updated to Xcode 7. I am also using Swift in my project. I’ve updated to aubio 0.4.2. I'm using the iOS Universal framework download.

If I set aubio as an optional framework it loads the rest of the app but then crashes on new_aubio_pitch()

**Comment by piem** [comment]
Hi @adamski 

the iosuniversal framework at http://aubio.org/download was wrongly created using a dynamic version of the library. I updated it with a static one.

Let  me know if it helps!

Best, Paul

**Comment by adamski** [comment]
There is an `aubio` subfolder in the `Headers` folder. So I had to change the header include to `aubio/aubio/aubio.h` to get it to compile. 

Also it has not been compiled with Bitcode enabled (new in Xcode 7). This means that any iOS projects using it will need to be compiled with Bitcode disabled. Please, if possible compile with Bitcode enabled. Currently its throwing an error if I disable Bitcode for my project: 

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: input file must be a linked Mach-O file not an archive: path-to/aubio-0.4.2.iosuniversal_framework/aubio.framework/aubio (for architecture armv7)
error: bitcode_strip path-to/aubio-0.4.2.iosuniversal_framework/aubio.framework/aubio: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip exited with 1
```
This may be to do with the nested folder..

**Comment by piem** [comment]
ok, i updated the ios universal framework again, this should fix the header location.

did you mean "Currently its throwing an error if I **en**able Bitcode" ?

**Comment by adamski** [comment]
The error has now been fixed in the latest version, thanks. 
However, I need to disable bitcode for the project in order for it to compile in Xcode 7.

**Comment by piem** [comment]
ok, thanks for the feedback
