### ISSUE TITLE
Entry point 'new_aubio_source' could not be found

### ISSUE THREAD

**Issue by mgomez00** [aubio/aubio#306]
Hellow,
I downloaded the aubio files and generated (C#) the solution. Next I am trying to run the project Aubio.NET.TestTempo And I get yhe error "Entry point 'new_aubio_source' could not be found in the DLL file 'aubio'"  on line 27 od SOURCE.CS: "public unsafe Source(string uri, int sampleRate, int hopSize)
            : this(new_aubio_source(uri, sampleRate.ToUInt32(), hopSize.ToUInt32()))"

I am not a C# expert 
![Image](https://user-images.githubusercontent.com/69732529/90320800-21575b80-df12-11ea-99fe-b5d460129b60.jpg)

and I ask if somebody can help on the origin and solution of this error.

Thanks in advance.

**Comment by piem** [comment]
hi @mgomez00 

how did you solve this issue? thanks for your feedback,

piem

**Comment by mgomez00** [comment]
I could not solve it. I researched in many sites and couldn't find a
solution.
I closed the post because after a few days nobody replied to it.
Thanks for your interest.

**Comment by piem** [comment]
hi @mgomez00 

not many people used aubio in C#, but you might want to take a look at what @aybe did here: https://github.com/aybe/aubio.net

cheers, piem

**Comment by mgomez00** [comment]
I will.
Thanks very much.
