### ISSUE TITLE
I can't use aubio on window 10/py37

### ISSUE THREAD

**Issue by biensuur** [aubio/aubio#307]
1.
i download aubio by `pip install aubio`
when i checked and write `aubio` in terminal, it always print:
`from ._aubio import __version__ as version`
`UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 945-946: invalid continuation byte`

and i have already set 'Beta: Use Unicode-UTF8 for worldwide language support' in my system, but it doesn't work.

2.
i have downloaded 'aubio-0.4.6-win64', but i don't konw how to use it... 

how should i solve it or is there a easy way to use aubio on window10(i am a newbie, i may miss some important ways to build and install aubio), please help me bro, i have tried to make it for a week

thanks, biensuur

**Comment by piem** [comment]
howdy,

this is long standing issue related to encoding on windows.

could you check if you can rebuild python-aubio after replacing the `~` by a `-` in `VERSION` ?

this patch should do it for you:

```patch
diff --git a/VERSION b/VERSION
index 8fa7caab..5a03d28d 100644
--- a/VERSION
+++ b/VERSION
@@ -1,7 +1,7 @@
 AUBIO_MAJOR_VERSION=0
 AUBIO_MINOR_VERSION=5
 AUBIO_PATCH_VERSION=0
-AUBIO_VERSION_STATUS='~alpha'
+AUBIO_VERSION_STATUS='-alpha'
 LIBAUBIO_LT_CUR=5
 LIBAUBIO_LT_REV=4
 LIBAUBIO_LT_AGE=8
```

see also issues #285, #293, and #266

thanks, piem

**Comment by biensuur** [comment]
Thanks for replying me, i totally make it, you're my hero!!!
