### ISSUE TITLE
pitch documentation python

### ISSUE THREAD

**Issue by jon044** [aubio/aubio#308]
I've been trying to capture the pitch of a .wav file I keep getting the error of "RuntimeError: failed creating pitch".

Here's the code:
import aubio
method = "testfile2.wav"
b = aubio.pitch(method, 2048, 512, 44100)
 
There doesn't seem to be very much of an explanation on how to use pitch on the python docs, so I'm pretty confused.

**Comment by piem** [comment]
hi @jon044 

```
>>> import aubio
>>> help(aubio.pitch)
Help on class pitch in module aubio:

class pitch(builtins.object)
 |  pitch(method="default", buf_size=1024, hop_size=512, samplerate=44100)
 |  
 |  Pitch detection.
 |  
 |  Supported methods: `yinfft`, `yin`, `yinfast`, `fcomb`, `mcomb`,
 |  `schmitt`, `specacf`, `default` (`yinfft`).
[...]
```

should answer your question.

cheers, piem

**Comment by piem** [comment]
also, for a fully fledged example, check out `python/demos/demo_pitch.py`

best, piem

**Comment by jon044** [comment]
Thank you very much Piem. Great module you've got.
