### ISSUE TITLE
Unable to find versioned dylibs (MacOS)

### ISSUE THREAD

**Issue by rec** [aubio/aubio#317]
Hello, and thanks for what promises to be a really interesting package!

I've tried to install aubio using pip, brew and conda, and each time I get the same sort of error, which leads me to believe the problem isn't with any of those.

For some reason, it's requesting a specific version number of some dylibs, which  then can't be found (because my version is newer).

----

For example, `pip` gives this:

```
>>> import aubio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tom/.virtualenvs/sorta/lib/python3.8/site-packages/aubio/__init__.py", line 26, in <module>
    from ._aubio import __version__ as version
ImportError: dlopen(/Users/tom/.virtualenvs/sorta/lib/python3.8/site-packages/aubio/_aubio.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/x265/lib/libx265.169.dylib
  Referenced from: /usr/local/opt/ffmpeg/lib/libavcodec.58.dylib
  Reason: image not found
```

Now `/usr/local/opt/x265/lib/libx265.169.dylib` indeed does not exist, but `libx265.192.dylib` does.  

The dynamic loading really shouldn't use a specific version, it should use the symlink `/usr/local/opt/x265/lib/libx265.dylib`.

For fun, I tried creating a symlink for the missing dylib, and that got me a bit further, but three symlinks later, it was clearly a long slog and a _bad_ idea in the first place.

----

The conda error is very similar:

```
ImportError: dlopen(/Users/tom/anaconda3/lib/python3.8/site-packages/aubio/_aubio.cpython-38-darwin.so, 2): Library not loaded: @rpath/libopenh264.5.dylib
  Referenced from: /Users/tom/anaconda3/lib/libavcodec.58.dylib
  Reason: image not found
```

Same results when checking - I do have that library, but a slightly later version of it, not the specific one.

This error _does_ use a different, fresh copy of `/Users/tom/anaconda3/lib/libavcodec.58.dylib` that I just installed with Anaconda, so that damps the theory that it's a broken `libavcodec`.

Any thoughts?  I'm very open to it being a misconfiguration of my machine.  

I just imported `numpy` without problems from that same Python so I can dynamically load at least sometimes...

* System Version:	macOS 10.14.6 (18G103)
* Kernel Version:	Darwin 18.7.0

**Comment by piem** [comment]
Hi @rec,

the python module for aubio can be built in 2 different ways:

 - using waf (shared library), then pip (linking the aubio module against libaubio)
 - using pip (python module only).

in both cases, the linker flags are derived from using `pkg-config --libs`.

Could you first try building [aubio 0.4.9](https://aubio.org/pub/aubio-0.4.9.tar.bz2) and running the binaries like `aubioonset`?

cheers, piem

**Comment by rec** [comment]
Hello, and thanks for your time and effort here!  C++ builds are non-trivial.  :-/

---

Same class of error (full log attached below).

I skimmed the log.

I see these warnings around the middle

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: src/libaubio.a(audio_unit.c.1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: src/libaubio.a(dct_fftw.c.1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: src/libaubio.a(dct_ipp.c.1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: src/libaubio.a(dct_ooura.c.1.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: src/libaubio.a(windll.c.1.o) has no symbols
```

which to me means just that some features aren't being compiled in perhaps?, but doesn't explain it, and later this error:

```
stderr:
dyld: Library not loaded: /usr/local/opt/x265/lib/libx265.169.dylib
  Referenced from: /usr/local/opt/ffmpeg/lib/libavcodec.58.dylib
  Reason: image not found
```


[results.txt](https://github.com/aubio/aubio/files/5552955/results.txt)

**Comment by rec** [comment]
I should add that I do a lot of C++ compilation on different projects on this machine without issue, but precisely by that token there might also be something obscure going on.

The option of running this in docker is also available to me, and might save a lot of everyone's time.

**Comment by rec** [comment]
Ah, sorry for all the traffic but I tried running `pkg-config` with perhaps interesting results I can't really interpret.

```
$ pkg-config --libs libavcodec
-L/usr/local/Cellar/ffmpeg/4.1.3_1/lib -lavcodec

$ pkg-config --libs libx265
Package libx265 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libx265.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libx265' found
```

I have that library installed in `/usr/local/opt/x265/`, but there is no `libx265.pc` anywhere in it.  I tried putting `/usr/local/opt/x265/lib/` and `/usr/local/opt/x265/` in the `PKG_CONFIG_PATH` but no change.

Cheers!

**Comment by piem** [comment]
thanks for the additional info @rec. it seems that the installation of libav on your system is somehow incomplete or broken.

reinstalling `ffmpeg` on your system should pull `x265` on which it depends.
 
otherwise you should be able to build aubio without libav with adding this option: `--disable-avcodec`

as a side note aubio is written in C, no C++ involved here ;)

**Comment by rec** [comment]
C... C... I remember this from my long-distant childhood.  ;-)

Strong detective work which has the ring of truth.  I'll report back.

**Comment by rec** [comment]
Well, that was pointlessly involved.

It turned out that several parts of my brew installation were broken.  Why?  I have no idea, I have been scrupulous.

In the event I also had to `brew uninstall libav` to get it all to work _and_ I had to clear Pip's &*$#$@ cache with `pip cache remove aubio` (gotcha!)

In case someone else runs into this, the important parts were, I believe, these ones:

```
brew uninstall ffmpeg
brew uninstall libav
pip uninstall aubio
pip cache remove aubio

brew install ffmpeg
brew install libav
pip install aubio
```

---

I'm ready to close this but one more question - does `import aubio` import all the dynamic libraries, or is there some way to trigger loading more, later?

I want to make sure that all the dylibs are firing on all cylinders...

**Comment by piem** [comment]
hi @rec 

glad you sorted it out.
yes, all libraries are loaded when the python interpreter executes `import aubio`

that is all the libraries built against your install of aubio. you can get a list of them by running something like:

`$ otool -L $VIRTUAL_ENV/lib/python*/site-packages/aubio/_aubio.so`

hth, piem

**Comment by rec** [comment]
Excellent!  Thanks for leading me to the solution.

**Comment by rec** [comment]
Just a note that I was able to reproduce this issue through the compilation error of #320! and then simply:

```
pip uninstall aubio
pip cache remove aubio
```

got me back into a good state.

So I don't think the `brew` operations above are needed.
