### ISSUE TITLE
Arduino Compatibility

### ISSUE THREAD

**Issue by emersont1** [aubio/aubio#32]
Is this Library arduino compatible or does it rely on incompatible libraries?

**Comment by piem** [comment]
Hi @emersont1,

aubio can be compiled with **no** external dependencies, so it should work fine on arduino too.

Let us know how it goes!

**Comment by emersont1** [comment]
Just as a confirmation, is it polyphonic?

**Comment by piem** [comment]
no, only monophonic for now.

**Comment by emersont1** [comment]
Is polyphonics planned, and if so, on what kind of time scale

**Comment by piem** [comment]
yes, definitely planned, no time scale defined yet.

let's take this discussion to aubio-user: https://aubio.org/contact

**Comment by emersont1** [comment]
Okay. You can close this

**Comment by piem** [comment]
great, welcome!

**Comment by piem** [comment]
great, welcome!
