### ISSUE TITLE
public key of Thomas Nagy has expired 

### ISSUE THREAD

**Issue by chensisi0730** [aubio/aubio#325]
aubio$ make
make[1]: Entering directory '/data3/code/github_code/onset_detection/c-cpp/audio2/aubio'
./scripts/get_waf.sh
/tmp/tmp.d1CydxZaKG /data3/code/github_code/onset_detection/c-cpp/audio2/aubio
gpg: key 22BE0C62FFBFA548: "Thomas Nagy <tnagy@waf.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: assuming signed data in 'waf-2.0.20.tar.bz2'
gpg: Signature made 2020年03月28日 星期六 16时57分43秒 CST
gpg:                using RSA key 8AF22DE5A06822E3474F3C7049B4C67C05277AAA
gpg: Can't check signature: No public key
Makefile:53: recipe for target 'getwaf' failed
make[1]: *** [getwaf] Error 1
make[1]: Leaving directory '/data3/code/github_code/onset_detection/c-cpp/audio2/aubio'
Makefile:50: recipe for target 'checkwaf' failed
make: *** [checkwaf] Error 2

**Comment by chilinhnet** [comment]
same problem with me

**Comment by piem** [comment]
thanks for the report! i meant to close this via the commit message,

cheers, piem
