### ISSUE TITLE
./waf configure --enable-fftw3f    

### ISSUE THREAD

**Issue by chensisi0730** [aubio/aubio#326]
run   command  "./waf configure --enable-fftw3f    "  failed 
Checking if complex.h is enabled         : no
Checking for program 'pkg-config'        : /usr/bin/pkg-config
Checking for 'fftw3f'                    : not found
The configuration failed

**Comment by piem** [comment]
hi @chensisi0730 

you are asking waf to build aubio using fftw3, but the fftw3 library was not found, so the configuration failed.

i see no issue here. please elaborate if you were expecting some other behavior.

cheers, piem
