### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [aubio/aubio#35]
I would like to point out that identifiers like "[`_AUBIO_PEAKPICK_H`](https://github.com/aubio/aubio/blob/ec3792c18716c6a9c5acf8c2d6e571199c4b6d62/src/onset/peakpicker.h#L29)" and "[`_AUBIO_RESAMPLER_H`](https://github.com/aubio/aubio/blob/ec3792c18716c6a9c5acf8c2d6e571199c4b6d62/src/temporal/resampler.h#L21)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by piem** [comment]
hi @elfring 

ok, i believe this would match all the clashing macro names:

    $ git ls | xargs egrep "#(define|ifndef|endif.*) _"

while preserving the ones aimed at the pre-processor:

    $ git ls | xargs egrep "#ifdef _"

Now, what about file scope objects such as `struct _aubio_resampler_t { ... }` ?

**Comment by elfring** [comment]
Did your software fiddle with [the reserved name space](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") in inappropriate ways only for some include guards?

**Comment by piem** [comment]
yes, there are have a few more clashes:

 - All identifiers that begin with an underscore (1999 C)
 - Each name that contains a double underscore (2003 C++)
 - Names that end with `_t` (POSIX)

See also [GNU libc's reserved names](http://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/Reserved-Names.html).

**Comment by piem** [comment]
After @6f42c16, we are know at:

 - ~~All identifiers that begin with an underscore (1999 C)~~
 - ~~Each name that contains a double underscore (2003 C++)~~
 - Names that end with `_t` (POSIX)

No plans to fix the latest for now. Hopefully we won't clash with a future POSIX! :)

See also [this discussion](http://stackoverflow.com/questions/3225386/if-i-do-a-typedef-in-c-or-c-when-should-i-add-t-at-the-end-of-typedefed).

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/aubio/aubio/commit/6f42c16 "Renaming of include guards").
