### ISSUE TITLE
Mondo Issue with Running in C++

### ISSUE THREAD

**Issue by HarrisonLeece** [aubio/aubio#351]
Hey bros, I hope you are catching gnarly wavs out here.

I'm trying to learn the virtual waves and surf the Sea (plus plus).  So like I built and installed aubio into usr/local and have my include statement (the compiles): #include <aubio/aubio.h>.  I know in the examples in the docs, the include is simply #include <aubio.h>, but that doesn't compile for me.   When I compile with this and the fft test at https://aubio.org/doc/latest/spectral_2test-fft_8c-example.html

I get undefined reference errors for every aubio data type.  Do you kooks know how I can define my references?  I was hoping simply using namespace aubio would fix the errors but no luck.

:call_me_hand:

**Comment by piem** [comment]
howdy,

for the headers, yes, they should `#include <aubio/aubio.h>` with `-I/«prefix»/include`

for the  symbols, you'll need to link against libaubio (`-L/«prefix»/lib -laubio`)

you could use `pkg-config` to get the correct flags. here is a quick example:

1. build and install aubio
```
$ cd aubio 
$ ./scripts/get_waf.sh && ./waf distclean configure build install --prefix=/tmp/aubio
```
2. set and check pkg-config path
```
$ export PKG_CONFIG_PATH=/tmp/aubio/lib/pkgconfig
$ pkg-config --libs --cflags aubio
-I/tmp/aubio/include -L/tmp/aubio/lib -laubio
```

and yeah, it's C, not C++, so no namespace.

hth, cheers, piem

**Comment by HarrisonLeece** [comment]
Thanks bro, I guess I forgot to add -laubio to my build script.  This is my second c program, so I appreciate the write up.
