### ISSUE TITLE
fails to build with ffmpeg 5.0

### ISSUE THREAD

**Issue by berolinux** [aubio/aubio#353]
aubio fails to build with the recently released ffmpeg 5.0.

All the code needed to handle ffmpeg 5.0 is already there, but ifdef-ed out in a condition that is never activated.

```
#if LIBAVCODEC_VERSION_MAJOR >= 59
#define FF_API_LAVF_AVCTX 1
#endif
```

is all it takes.

**Comment by dvzrv** [comment]
We are currently also attempting rebuilds against ffmpeg 5.0 on Arch Linux.

@piem can this be fixed and a new release be made? It has been some time since the last one after all :)

**Comment by piem** [comment]
thanks for the report @berolinux 

@dvzrv let us know if that fixes it for you, i'll merge that in master, which should be in a good state to release

**Comment by berolinux** [comment]
Works here. An equivalent patch has been in the OpenMandriva package for a couple of days.

**Comment by dvzrv** [comment]
@piem thanks, this also works for me. A new release would be much appreciated, as 0.4.9 is rather old by now.
