### ISSUE TITLE
converting audio data from audio driver to aubio format

### ISSUE THREAD

**Issue by feltrinm** [aubio/aubio#36]
Hi guys, I'm using aubio library to detect some audio features, in particularly I'm using aubio_onsets to detect onsets of an audio stream coming from a microphone (with ALSA library). Now I've necessity to put in a fvec_t a windowed part of the stream audio, but I don't know which format aubio_onset use to analize audio. Currently I put in the fvec_t data in signed 16bit format (with opportune cast from short to float) but the aubio_onsets_do function return value 4 (when it should be return 0 or a value included from 1 to 2) and I don't understand why. Can you help me to find where is the problem?? 

Thank's.

**Comment by piem** [comment]
Hi @feltrinm,

`fvec_t` vectors contain floating point numbers (`smpl_t` aka `float`). In `aubio_onset_do` and everywhere else in aubio, audio data is expected to be a float in the interval [-1; 1].

You should be able to convert your integer data like so:
```c
    #define INT_TO_FLOAT 3.0517578125e-05 // = 1. / 32768.
    float fsample = (float) isample * INT_TO_FLOAT;
```
Let us know how it goes!

**Comment by piem** [comment]
Hi @feltrinm 

I guess this can be closed for now. Please reopen if you have more questions.

Best, Paul
