### ISSUE TITLE
Aubio PItch Passing Audio File 

### ISSUE THREAD

**Issue by christinaliao11** [aubio/aubio#360]
Hi I am trying to analyze pitch alongside the timestamp using audiopitch. I found code online that would allow me to do it, but I am trying to pass an audio file to aubio. Does anyone know how to do this?

![Screen Shot 2022-05-03 at 12 09 31 AM](https://user-images.githubusercontent.com/52087358/166403690-274266f2-9fe3-4104-a509-b6665266abf0.jpg)

**Comment by piem** [comment]
hi @christinaliao11 

you will want to use `aubio.source`. check out the demos to find out how!

cheers, piem
