### ISSUE TITLE
iOS framework needs M1 processor slice to compile for all iOS devices

### ISSUE THREAD

**Issue by bowener** [aubio/aubio#361]
My iOS app is broken on new M1 iPads, and I'm afraid I'm not clever enough to create a new framework project myself with the source code...

**Comment by jscalo** [comment]
With the above commits is this still an issue?

**Comment by bowener** [comment]
HI John

YEs, the iOS app was able to compile and run on an M1 iPad.  The only remaining issue was the inability to natively debug on and M1 Mac laptop.  The only way to get that to happen was to invoke Rosetta when using XCODE

Thanks/Rob

**Comment by quentinhayot** [comment]
Using Xcode with Rosetta is no longer possible with MacOS Ventura :/
