### ISSUE TITLE
would you accept a patch to build wheels?

### ISSUE THREAD

**Issue by illume** [aubio/aubio#370]
Hello,

> Python wheels are great. Building them across Mac, Linux, Windows, on multiple versions of Python, is not.

[cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) does all of this by pasting a bit of config for github actions. It's quite spiffy.

Let me know if you'd accept a patch for this, and I'll whip one up in a jiffy!

ciao,

**Comment by piem** [comment]
hi @illume 

any reason why you closed this issue already? i haven't looked at this project yet, but reading a (small) patch would make answering the question easier.

cheers, piem
