### ISSUE TITLE
pitch detection for wind instruments

### ISSUE THREAD

**Issue by Greg767** [aubio/aubio#39]
Hi,

As the title says, I'd like to make a good pitch detection for wind instruments (real-time detection). So I have to deal with finding the fundamental amongst many harmonics.
Could you please advise me on what methods to use?

Thank you very much.

**Comment by piem** [comment]
Hi @Greg767 

yinfft is one of the most robust methods to get the pitch in transient sounds, but since the transients are often short in wind instruments, you might get good results as well using simpler methods such as `fcomb` or even `schmitt` (the most computationally efficient).

You can have a look at Chapter 3 of my [thesis](https://aubio.org/phd), where results for different types of sounds are given.

Your mileage will vary. Let us know how it goes!

best, Paul

**Comment by Greg767** [comment]
Hi @piem ,
Thanks a lot for your response and reference to your thesis which I will read.
Last year I could develop a working prototype that had good results with yinfft, but I hit a limit in analyze time.
What I found out is that the sound should be held at least for 600ms so that it can be analyzed accurately. Notes shorter than that don't get recognized or get inaccurately recognized.

I would be very interested to know if you have some kind of comparative measures in this field because that would give me an idea if I didn't set up aubio correctly or the method I use to analyze the incoming sound is not optimal.

I made the tests using recorded sound from a clarinet that plays a melody and compared the analyzed sound to the pitches I read from a music score.

Thanks,
Gergely

**Comment by piem** [comment]
hi @Greg767 

600ms sounds like a long time. what hop_size / win_size are you using ?

for instance, if you use a hop size of 256, you would get about 100 pitch candidates over 600ms at 44100Hz.

the window size should be adjusted on the lowest frequency you want to detect. 2048 or 4096 is generally enough at 44100Hz.

out of these 100 candidates, at least some of them should be correct.

did you annotate the recorded sounds manually frame by frame for comparison ?

best, Paul

**Comment by piem** [comment]
hi @Greg767 

I hope I addressed most of your questions. Please re-open this issue if needed.

best, piem

**Comment by Greg767** [comment]
hi @piem
Thanks for getting back. The project is on hold at the moment, but when it reactivates probably I will get back to you!
Best regards,
Greg
