### ISSUE TITLE
Can not install aubio - Failed building wheel for aubio

### ISSUE THREAD

**Issue by JohnnyKlausi** [aubio/aubio#390]
Hi, i am trying to install aubio but can't do it. I tried several ways, including **pip install aubio**, installing from source code **python setup.py install** both in windows command prompt and in pyCharm. The Error message reads:

> Collecting aubio
>   Using cached aubio-0.4.9.tar.gz (479 kB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: numpy in c:\users\johnny\pycharmprojects\first\venv\lib\site-packages (from aubio) (1.24.3)
> Building wheels for collected packages: aubio
>   Building wheel for aubio (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [97 lines of output]
>       C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
>       !!
>       
>               ********************************************************************************
>               Requirements should be satisfied by a PEP 517 installer.
>               If you are using pip, you can try `pip install --use-pep517`.
>               ********************************************************************************
>      
>       !!
>         dist.fetch_build_eggs(dist.setup_requires)
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build\lib.win-amd64-cpython-311
>       creating build\lib.win-amd64-cpython-311\aubio
>       copying python\lib\aubio\cmd.py -> build\lib.win-amd64-cpython-311\aubio
>       copying python\lib\aubio\cut.py -> build\lib.win-amd64-cpython-311\aubio
>       copying python\lib\aubio\midiconv.py -> build\lib.win-amd64-cpython-311\aubio
>       copying python\lib\aubio\slicing.py -> build\lib.win-amd64-cpython-311\aubio
>       copying python\lib\aubio\__init__.py -> build\lib.win-amd64-cpython-311\aubio
>       running build_ext
>       checking for aubio = 0.4.9
>       Running "pkg-config --libs --cflags aubio = 0.4.9" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
>       Info: aubio 0.4.9 was not found by pkg-config
>       Info: looking for *optional* additional packages
>       checking for libavcodec
>       Running "pkg-config --libs --cflags libavcodec" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
>       checking for libavformat
>       Running "pkg-config --libs --cflags libavformat" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
>       checking for libavutil
>       Running "pkg-config --libs --cflags libavutil" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
>       checking for libswresample
>       Running "pkg-config --libs --cflags libswresample" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
>       checking for libavresample
>       Running "pkg-config --libs --cflags libavresample" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
>       checking for sndfile
>       Running "pkg-config --libs --cflags sndfile" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
>       checking for samplerate
>       Running "pkg-config --libs --cflags samplerate" failed: FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden', None, 2, None)
>       Info: libaubio was not installed or built locally with waf, adding src/
>       Running command: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe -E -DAUBIO_UNSTABLE=1 -Isrc src\aubio.h
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\Johnny\AppData\Local\Temp\pip-install-vkw3iyv3\aubio_e48fbedfbba34aa597f606e1023a8b30\setup.py", line 70, in <module>
>           distrib = setup(name='aubio',
>                     ^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\__init__.py", line 107, in setup
>           return distutils.core.setup(**attrs)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>           return run_commands(dist)
>                  ^^^^^^^^^^^^^^^^^^
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>           dist.run_commands()
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>           self.run_command(cmd)
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
>           super().run_command(command)
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
>           self.run_command("build")
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
>           super().run_command(command)
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
>           self.run_command(cmd_name)
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
>           super().run_command(command)
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
>           self.build_extensions()
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
>           self._build_extensions_serial()
>         File "C:\Users\Johnny\PycharmProjects\first\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
>         File "C:\Users\Johnny\AppData\Local\Temp\pip-install-vkw3iyv3\aubio_e48fbedfbba34aa597f606e1023a8b30\python\lib\moresetuptools.py", line 191, in build_extension
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\Johnny\AppData\Local\Temp\pip-install-vkw3iyv3\aubio_e48fbedfbba34aa597f606e1023a8b30\python\lib\gen_external.py", line 271, in generate_external
>           c_declarations = get_c_declarations(header, usedouble=usedouble)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\Johnny\AppData\Local\Temp\pip-install-vkw3iyv3\aubio_e48fbedfbba34aa597f606e1023a8b30\python\lib\gen_external.py", line 101, in get_c_declarations
>           cpp_output = get_cpp_output(header=header, usedouble=usedouble)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\Johnny\AppData\Local\Temp\pip-install-vkw3iyv3\aubio_e48fbedfbba34aa597f606e1023a8b30\python\lib\gen_external.py", line 129, in get_cpp_output
>           % err_output.decode('utf8'))
>             ^^^^^^^^^^^^^^^^^^^^^^^^^
>       UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 62: invalid start byte
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for aubio
>   Running setup.py clean for aubio
> Failed to build aubio
> ERROR: Could not build wheels for aubio, which is required to install pyproject.toml-based projects

I installed and updated Visual Studio Build Tools (now I got 2022 on Version 17.6.2 and 2017 on 15.9.54) and updated **pip install --upgrade setuptools** and several other stuff. Nothing changed.

I am on Windows 10, using PyCharm 2023.1 (Community Edition), Interpreter is Python 3.11

I succesfully installed aubio with conda but now I am too dumb to use it in PyCharm..., when I use conda as interpreter and do pip show aubio it's not installed. When I run pip install aubio it's the same error as above. It seems I did not understand the concept of venvs yet.

Can somebody help me? Thank you very much

**Comment by JohnnyKlausi** [comment]
I am sorry, I just needed to restart pyCharm. Now it gives me an aubio version when I use anaconda3 as interpreter and do **pip show aubio**
Maybe this ist still relevant for a fix? For me it's good now, sorry.

**Comment by piem** [comment]
ok, thanks for the followup @JohnnyKlausi
