### ISSUE TITLE
Python compatibility problems (waf, python3)

### ISSUE THREAD

**Issue by starius** [aubio/aubio#41]
aubio [unpacks waflib](https://github.com/aubio/aubio/blob/master/Makefile) from waf file. waf [is known](https://github.com/waf-project/waf/issues/1677#issuecomment-168491796) to produce waflib processed for current Python version. waflib is included into aubio distribution.

As a result, if Python version installed on the machine making aubio distribution differs from Python version on build machine, the waf can [fail](https://github.com/mxe/mxe/issues/1108#issuecomment-168340558) with Python syntax errors.

To be compatible with more Python versions on build machines, please include file "waf" as is instead of unpacking waflib from it.

**Comment by piem** [comment]
Hi Boris,

what happens if you run 'make getwaf' again?

cheers, Paul

**Comment by starius** [comment]
If I run `make getwaf` with python=python2, nothing changes.

If I run `make getwaf` with python=python3, it produces the error:
```
mv: cannot stat ‘.waf-*/waflib’: No such file or directory
```
Waf unpacks itself to directory `.waf3-*` for Python 3.

**Comment by piem** [comment]
This should be fixed in the develop branch with e06ac8f and 0e39e88.

**Comment by starius** [comment]
Why not to unpack tar archive instead? Files produced by `waf --help` differ from files in tar archive. And the latter seem to be more portable.

From https://github.com/waf-project/waf/issues/1677#issuecomment-168496448:
> Yet, if your intention is to ship such files, then you should really use the files from the tar archive.

**Comment by piem** [comment]
I ended up unpacking the waflib directory only when asked to. This should work with python3. See @81ad5771

best, Paul

**Comment by piem** [comment]
aubio is now being tested on python 2.7 and 3.4, let me know if you discover any issues!
