### ISSUE TITLE
build_apple_frameworks fails when a space is in the path 

### ISSUE THREAD

**Issue by piem** [aubio/aubio#43]
see comments from @dantarakan in #34

**Comment by josephmartz** [comment]
still rocking bits uh? all the love <3

**Comment by piem** [comment]
hey @josephmartz :-)

@dantarakan, this should be fixed in the develop branch now.

cheers, piem

**Comment by dantarakan** [comment]
@piem , I'm terribly sorry for not checking this earlier, it has totally escaped my mind!
Everything works fine now, thanks for your hard work!
