### ISSUE TITLE
undefined symbol: aubio_sink_close while running aubio using python

### ISSUE THREAD

**Issue by vyassu** [aubio/aubio#45]
I am encountering the below mentioned 
ImportError: /home/vyassu/.python-eggs/aubio-0.4.2a0-py2.7-linux-x86_64.egg-tmp/aubio/_aubio.so: undefined symbol: aubio_sink_close

**Comment by piem** [comment]
Hi @vyassu  

I can't reproduce this. How did you build that version of aubio?

**Comment by vyassu** [comment]
I have followed the exact same thing mentioned in the document. Can you please provide the scripts to uninstall the entire setup and can initiate the same once again.

**Comment by piem** [comment]
just remove the egg files altogether:

    $ rm -rf ~/.python-eggs/aubio*

did you compile 0.4.2 or develop? where did you install libaubio?

**Comment by vyassu** [comment]
I tried reinstalling .. and this time it worked.
Only thing I did extra was that I removed an old version installed along with ubuntu package.

Thank you Guys!!
