### ISSUE TITLE
No conda build for OS X?

### ISSUE THREAD

**Issue by tbeddy** [aubio/aubio#47]
When trying to install aubio through conda:
`conda install --channel https://conda.anaconda.org/piem aubio`
I get this error.
`Error:  Package missing in current osx-64 channels: - aubio`
It looks like conda only has Linux builds. Would making an OS X package for conda be a trivial task?

**Comment by piem** [comment]
Hi @tbeddy ,

I just uploaded a draft version on https://conda.anaconda.org/piem.

Let me know if it works.

Unfortunately, the build is failing unless libaubio is already installed on the system for now.

best, Paul

**Comment by piem** [comment]
hi @tbeddy ,

did you get a chance to try the osx package?

thanks, Paul

**Comment by tbeddy** [comment]
Hi Paul,

Sorry to respond so late. I tried again and got this response:
`The following specifications were found to be in conflict:
  - aubio -> numpy
  - aubio -> python 2.7*
  - conda -> conda-env
  - conda -> pycosat
  - conda -> python 2.7*
  - conda -> pyyaml
  - conda -> requests
  - conda-env (target=conda-env-2.4.5-py35_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*
  - mkl-service (target=mkl-service-1.1.2-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - nose (target=nose-1.3.7-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - numexpr (target=numexpr-2.5-np110py35_0.tar.bz2) -> numpy 1.10*|1.11*|1.6*|1.7*|1.8*|1.9*
  - numexpr (target=numexpr-2.5-np110py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - numpy (target=numpy-1.10.4-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - pip (target=pip-8.1.1-py35_1.tar.bz2) -> python 2.7*
  - pip (target=pip-8.1.1-py35_1.tar.bz2) -> setuptools
  - pip (target=pip-8.1.1-py35_1.tar.bz2) -> wheel
  - pycosat (target=pycosat-0.6.1-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - python 3.5*
  - pyyaml (target=pyyaml-3.11-py35_1.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - requests (target=requests-2.9.1-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - scikit-learn (target=scikit-learn-0.17.1-np110py35_0.tar.bz2) -> nose
  - scikit-learn (target=scikit-learn-0.17.1-np110py35_0.tar.bz2) -> numpy 1.10*|1.11*|1.5*|1.6*|1.7*|1.8*|1.9*
  - scikit-learn (target=scikit-learn-0.17.1-np110py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - scikit-learn (target=scikit-learn-0.17.1-np110py35_0.tar.bz2) -> scipy
  - scipy (target=scipy-0.17.0-np110py35_0.tar.bz2) -> numpy 1.10*|1.11*|1.5*|1.6*|1.7*|1.8*|1.9*
  - scipy (target=scipy-0.17.0-np110py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - setuptools (target=setuptools-20.7.0-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - wheel (target=wheel-0.29.0-py35_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*
Use "conda info <package>" to see the dependencies for each package.`

Do you think this is more likely an issue with my Python setup?

**Comment by piem** [comment]
hi,

aubio is no on conda-forge, so this issue should be closed.

cheers, piem
