### ISSUE TITLE
Filterbank object - unclear how to use with other modules.

### ISSUE THREAD

**Issue by Craig-J** [aubio/aubio#48]
I'm currently stumped at how to get the filterbank object to work with the onset object.

As far as I can tell filterbank takes a spectrum and outputs a single sample for each filter but the onset object requires hop size number of samples...

I first thought to use the phase vocoder to generate the spectrum for input into the filterbank object - should I be doing it this way? It seems wrong though since the phase vocoder reduces hop size number of samples to one spectrum which then results in only one sample per filter (when hop size amount are required for the onset object). The onset object also does its own phase vocoding so it seems like this is a waste.

The only other way I can think of trying to use filterbank is to perform an fft on every single sample in the source and then piece together a buffer of hop size from each filter but it is painfully slow and as far as I can tell not working... making me think I'm doing this wrong somehow?

**Comment by piem** [comment]
Hi @Craig-J ,

The filterbank object does take a spetrum as input, and gives you one energy output per filter.

You can find an example here: https://github.com/aubio/aubio/blob/develop/python/demos/demo_mel-energy.py

The onset object takes an audio frame and does the spectral analysis on its own.

To build an onset detector on each band of a filterbank, you could try using the peak picker object, or write a new one instead.

Let us know if that helps!

Best, Paul

**Comment by Craig-J** [comment]
I ended up using https://github.com/vinniefalco/DSPFilters to filter the
source audio samples then performing onset detection on those instead.
Thank you for the reply. :]

On Mon, 18 Apr 2016 at 12:34 Paul Brossier <notifications@github.com> wrote:

> Hi @Craig-J <https://github.com/Craig-J> ,
>
> The filterbank object does take a spetrum as input, and gives you one
> energy output per filter.
>
> You can find an example here:
> https://github.com/aubio/aubio/blob/develop/python/demos/demo_mel-energy.py
>
> The onset object takes an audio frame and does the spectral analysis on
> its own.
>
> To build an onset detector on each band of a filterbank, you could try
> using the peak picker object, or write a new one instead.
>
> Let us know if that helps!
>
> Best, Paul
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/aubio/aubio/issues/48#issuecomment-211340821>
>
-- 
Thank you. :]
- Craig
