### ISSUE TITLE
how to estimate the bpm of a file?

### ISSUE THREAD

**Issue by piem** [aubio/aubio#52]
@xjefftang asked **how to get the bpm** of a file.

(He originally asked in #22 but couldn't open a new one, so opening a new bug for him here...)

**Comment by piem** [comment]
As I mentioned in #22, have a look at [demo_bpm_extract.py](https://github.com/aubio/aubio/blob/develop/python/demos/demo_bpm_extract.py#L45).

```python
    bpm_periods = 60./np.diffs(beats)
    bpm_median = np.mean(bpm_peridods)
```

**Comment by piem** [comment]
@xjefftang then asked in https://github.com/aubio/aubio/issues/22#issuecomment-214634309 *Did you find that median(bpms) generally is more accurate than mean(bpms)?*

Yes, very much so. The mean is very likely to give you a tempo period that is not in the original population of periods.

best, Paul

**Comment by xjefftang** [comment]
Great. Thanks for all your help, Paul. Much appreciated! 
Best,
Jeff
