### ISSUE TITLE
audio driver for iOS

### ISSUE THREAD

**Issue by billylo1** [aubio/aubio#57]
I managed to get a simple iOS app working and aubio was able to detect tempo from a new_aubio_source from a file.

Next step is to take input from the microphone instead of a source from a WAV file.  Any hints on creating a new_aubio_source that takes data from the microphone stream?  Use something like [AudioFileStreamID](https://developer.apple.com/library/mac/documentation/MusicAudio/Reference/AudioStreamReference/)?  I can record using standard AVAudioRecorder to a file; but my use case needs to handle live audio stream. 

In aubio, how can I process chunks of audio data as the microphone streams it the packets?

thanks in advance.

**Comment by piem** [comment]
Hi @billylo1 

You could use [`aubio_audio_unit`](/aubio/aubio/tree/master/src/io/audio_unit.h). You will need to `#define HAVE_AUBIO_UNSTABLE 1` before `#include <aubio/aubio.h>`.

If you want a fully fledged audio driver, try out <http://theamazingaudioengine.com/>.

Best, Paul

**Comment by billylo1** [comment]
thanks, Paul.
