### ISSUE TITLE
Requesting upgrade of the Debian package

### ISSUE THREAD

**Issue by hzulla** [aubio/aubio#59]
Hi @piem,

thanks a lot for aubio. The upcoming next release of [Sonic Pi](http://sonic-pi.net) will be [using aubio](https://github.com/aubio/aubio/issues/54) and its main target is Raspbian, which inherits its packages from Debian.

Could you please [upgrade the Debian package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828039) of aubio? That would be a great help.

Thank you very much!

**Comment by samaaron** [comment]
@piem just dropping by to say that Aubio is ace and I'm really enjoying integrating it into Sonic Pi - there are already a lot of exciting possibilities to be explored. My next live coding gig will feature heavy use of Aubio onset detection :-)

I also really look forward to getting this tech in the hands of kids all over the world. I think we'll be amazed to see what they can do with it.

**Comment by piem** [comment]
hi @hzulla and @samaaron ,

Thank you both for the nice feedback. Looking forward to hear and see more of what you are doing with aubio.

We are now approaching the release of 0.4.3 is  – a lot of changes! I should be able to submit it to the Debian archives soon after, hopefully before the middle of this month.

Best, Paul

**Comment by hzulla** [comment]
Cool. Thank you!

**Comment by hzulla** [comment]
Hi @piem - Sonic Pi is approaching an upcoming release. Do you have news regarding a package upgrade or would you accept patches to getting the Debian package updated to the current release from me?

**Comment by piem** [comment]
Hi @hzulla ,

I will make sure 0.4.3 is released before Sunday. The debian package will be updated soon after. Please test the master branch as much as you can in the mean time. Thanks for your patience.

Best, piem

**Comment by piem** [comment]
Hi @hzulla and @samaaron 

I tagged 0.4.3 yesterday. You should be able to build the new debian package (0.4.3-1) with git-buildpackage from:

    git://git.debian.org/collab-maint/aubio.git

I will upload this package soon to the debian archive.

Let us know it works for you,

Best, Paul

**Comment by samaaron** [comment]
This is great news, thanks! :-)

**Comment by hzulla** [comment]
@piem - could you release it to Debian sid, please?

**Comment by hzulla** [comment]
@piem - sorry, don't want to annoy you, but could you please look into this? It would be very helpful. Thank you!

**Comment by piem** [comment]
hi @hzulla, hi @samaaron,

i've just uploaded 0.4.3 to unstable: https://tracker.debian.org/news/813300

sorry for the lag, and let us know how it works for you!

best, Paul

**Comment by samaaron** [comment]
Thank-you so much!

We have now included aubio as a fundamental dependency to Sonic Pi (http://sonic-pi.net). We've only started making use of aubio - currently taking advantage of the onset detection. In Sonic Pi you can now do:

```
sample "/path/to/audio.flac", onset: 3
```

and Sonic Pi will play the 4th onset (thanks to aubio!!). We have this working on Mac, Windows and Linux :-)

So, thanks again for your amazing work - and I really think there's a lot more exciting stuff we can do with aubio going forward.
