### ISSUE TITLE
Aubio with line-in/microphone in realtime from python ?

### ISSUE THREAD

**Issue by stuaxo** [aubio/aubio#6]
Is it possible to use aubio with realtime audio in python - whether that's aubio interfacing with something like pulseaudio, or setting up all the audio in python, with e.g. pysoundcard (the new version of pyaudio) ?

https://github.com/bastibe/PySoundCard

**Comment by jhoelzl** [comment]
Hello,

i am trying to integrate the [pitch detection example](https://github.com/aubio/aubio/blob/master/python/demos/demo_pitch.py) into the [PyAudio record example](https://people.csail.mit.edu/hubert/pyaudio/):

```
"""PyAudio example: Record a few seconds of audio and save to a WAVE file."""


import pyaudio
import wave
import numpy as np
from aubio import pitch

CHUNK = 1024
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 16000
RECORD_SECONDS = 5
WAVE_OUTPUT_FILENAME = "output.wav"

p = pyaudio.PyAudio()

stream = p.open(format=FORMAT,
                channels=CHANNELS,
                rate=RATE,
                input=True,
                frames_per_buffer=CHUNK)

print("* recording")

frames = []

# Pitch
tolerance = 0.8
downsample = 1
win_s = 4096 // downsample # fft size
hop_s = 512  // downsample # hop size
pitch_o = pitch("yin", win_s, hop_s, RATE)
pitch_o.set_unit("midi")
pitch_o.set_tolerance(tolerance)


for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
    buffer = stream.read(CHUNK)
    frames.append(buffer)
   
    # Convert buffer to numpy data array
    signal = np.fromstring(buffer, dtype=np.int16)

    # Detect Pitch
    pitch = pitch_o(signal)[0]
    confidence = pitch_o.get_confidence()
    
    print("{} / {}".format(pitch,confidence))


print("* done recording")

stream.stop_stream()
stream.close()
p.terminate()

wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
wf.setnchannels(CHANNELS)
wf.setsampwidth(p.get_sample_size(FORMAT))
wf.setframerate(RATE)
wf.writeframes(b''.join(frames))
wf.close()
```

However, i get an error: 

>    pitch = pitch_o(signal)[0]
>ValueError: input array should be float

When i change 
`signal = np.fromstring(buffer, dtype=np.int16)` to `signal = np.fromstring(buffer, dtype='f')` the error disappears, but i only get this output (pitch /confidance):

> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan
> 16.7740325928 / nan

Any suggestions?

Thanks for support!

Regards,
Josef

**Comment by piem** [comment]
Hi @jhoelzl ,

what happens if you set ``FORMAT`` to ``pyaudio.paFloat32`` instead of ``pyaudio.paInt16`` ?

best, piem

**Comment by jhoelzl** [comment]
Hi @piem then i have to adjust `hop_s = 1024` otherwise i get error `ValueError: input size of pitch should be 512, not 1024`.

When i do this, the output of the loop is the same. I also tried `signal = np.fromstring(buffer, dtype=np.float32)`, but the output does not change.

**Comment by jhoelzl** [comment]
Hi @piem , thanks, yes now it works fine!

**Comment by piem** [comment]
great! can you post the working version here?

thanks, piem

**Comment by jhoelzl** [comment]
Of course, this is now working:

```
import pyaudio
import wave
import numpy as np
from aubio import pitch

CHUNK = 1024
FORMAT = pyaudio.paFloat32
CHANNELS = 1
RATE = 44100
RECORD_SECONDS = 5
WAVE_OUTPUT_FILENAME = "output.wav"

p = pyaudio.PyAudio()

stream = p.open(format=FORMAT,
                channels=CHANNELS,
                rate=RATE,
                input=True,
                frames_per_buffer=CHUNK)

print("* recording")

frames = []

# Pitch
tolerance = 0.8
downsample = 1
win_s = 4096 // downsample # fft size
hop_s = 1024  // downsample # hop size
pitch_o = pitch("yin", win_s, hop_s, RATE)
pitch_o.set_unit("midi")
pitch_o.set_tolerance(tolerance)


for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
    buffer = stream.read(CHUNK)
    frames.append(buffer)

    signal = np.fromstring(buffer, dtype=np.float32)
    
    pitch = pitch_o(signal)[0]
    confidence = pitch_o.get_confidence()
    
    print("{} / {}".format(pitch,confidence))


print("* done recording")

stream.stop_stream()
stream.close()
p.terminate()

wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
wf.setnchannels(CHANNELS)
wf.setsampwidth(p.get_sample_size(FORMAT))
wf.setframerate(RATE)
wf.writeframes(b''.join(frames))
wf.close()
```

**Comment by jhoelzl** [comment]
So now i have one more question.

The example code with PyAudio above works fine. However, when i integrate this into the [listen()](https://github.com/Uberi/speech_recognition/blob/master/speech_recognition/__init__.py#L463) function of the [SpeechRecognition](https://github.com/Uberi/speech_recognition) module (which also uses PyAudio), i always get an error when performing `pitch = pitch_o(signal)[0]`:

 ` ('Unexpected error:', <type 'exceptions.UnboundLocalError'>)`

I compared the input data array from the working example script with the listen() function, it has the same structure:

* `type(signal)` returns: `<type 'numpy.ndarray'>`
* `signal.shape` returns `(480,)`

In both scripts, PyAudio uses `FORMAT = pyaudio.paInt16`  and then i convert the values:

```
while True:
    buffer = stream.read(CHUNK)
    signal = np.fromstring(buffer, dtype=np.int16)
    signal = signal.astype(np.float32)
    #print(signal.shape)
    #print(signal)
    #print(type(signal))
    pitch = pitch_o(signal)[0]
    confidence = pitch_o.get_confidence()
```

In the example script, when the `hop_s` value has an incorrect number, `pitch_o()` correctly returns the error message:

> pitch = pitch_o(signal)[0]
> ValueError: input size of pitch should be 240, not 480 

But this does not happen in the listen() function, only this error appears:

` ('Unexpected error:', <type 'exceptions.UnboundLocalError'>)`

I assume the module is correctly loaded, because no error appears when performing this code:
```
import numpy as np
from aubio import pitch
...
...
# Pitch
tolerance = 0.8
downsample = 1
win_s = 4096 // downsample # fft size
hop_s = 480  // downsample # hop size
pitch_o = pitch("yin", win_s, hop_s, 16000)
pitch_o.set_unit("f0")
pitch_o.set_tolerance(tolerance)
...
...
```
Maybe somebody has an idea...

Regards,
Josef

**Comment by piem** [comment]
Hi @jhoelzl 

Would you mind opening a new issue for this? A more detailed code example showing where the exception is raised would help.

thanks, Paul

**Comment by jhoelzl** [comment]
@piem , sure, here: https://github.com/aubio/aubio/issues/67

**Comment by fbukevin** [comment]
Hi, guys.

I installed aubio python module and download the python demo [demo_onset.py](https://github.com/aubio/aubio/blob/master/python/demos/demo_onset.py). on both Windows 7 and Linux Mint(18.1). With Python version 3.6, when I use `python3 demo_onset.py test.mp3`, the error output was as following:

```
AUBIO ERROR: source_wavread: could not find RIFF header in test.mp3
AUBIO ERROR: source: failed creating aubio source with test.mp3 at samplerate 0 with hop_size 256
Traceback (most recent call last):
File "demo_onset.py", line 18, in <module>
s = source(filename, samplerate, hop_s)
RuntimeError: error creating source with "test.mp3"
```

I then installed ` libavcodec-dev libavformat-dev libavresample-dev libavutil-dev` and rebuild aubio with `./waf configure build` and `sudo ./waf install`, also export `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build/src`. But I got the same error still.

I got the same problem in python 2.7. Did I lose any step or prerequisite?

**Comment by piem** [comment]
Hi @fbukevin,

could you open please a new issue about mp3 with ffmpeg on windows?
also, please mention the output of 'pip install aubio' in your report.

thanks, piem

**Comment by fbukevin** [comment]
Hi @piem ,

Sure! 

Plz refer to #81

**Comment by SutirthaPhD** [comment]
> Of course, this is now working:
> 
> ```python
> #! /usr/bin/env python
> import pyaudio
> import wave
> import numpy as np
> from aubio import pitch
> 
> CHUNK = 1024
> FORMAT = pyaudio.paFloat32
> CHANNELS = 1
> RATE = 44100
> RECORD_SECONDS = 5
> WAVE_OUTPUT_FILENAME = "output.wav"
> 
> p = pyaudio.PyAudio()
> 
> stream = p.open(format=FORMAT,
>                 channels=CHANNELS,
>                 rate=RATE,
>                 input=True,
>                 frames_per_buffer=CHUNK)
> 
> print("* recording")
> 
> frames = []
> 
> # Pitch
> tolerance = 0.8
> downsample = 1
> win_s = 4096 // downsample # fft size
> hop_s = 1024  // downsample # hop size
> pitch_o = pitch("yin", win_s, hop_s, RATE)
> pitch_o.set_unit("midi")
> pitch_o.set_tolerance(tolerance)
> 
> 
> for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
>     buffer = stream.read(CHUNK)
>     frames.append(buffer)
> 
>     signal = np.fromstring(buffer, dtype=np.float32)
> 
>     pitch = pitch_o(signal)[0]
>     confidence = pitch_o.get_confidence()
> 
>     print("{} / {}".format(pitch,confidence))
> 
> 
> print("* done recording")
> 
> stream.stop_stream()
> stream.close()
> p.terminate()
> 
> wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
> wf.setnchannels(CHANNELS)
> wf.setsampwidth(p.get_sample_size(FORMAT))
> wf.setframerate(RATE)
> wf.writeframes(b''.join(frames))
> wf.close()
> ```

Can we do the similar to this Tap with beat ? Can anyone help please ?
