### ISSUE TITLE
No midi output from aubiotrack

### ISSUE THREAD

**Issue by topas-rec** [aubio/aubio#62]
When using aubiotrack in jack a jack midi port in aubio is present, but does not output any midi messages.

Expected behaviour:
Some kind of midi message at every point in time when an acoustical "ping" can be heard from the audio output of aubiotrack in jack.

Observed behaviour:
Together with jack (jack2) aubiotrack produces acoustic ping outputs through the audio output port in jack. When connecting a midi sniffer to the midi port no messages were emitted from the port.
Aubionotes for example emits the midi notes fine which can also be observed by a midi sniffer.

For the test kxstudio tools were used.

Thanks for making aubio open source.

**Comment by topas-rec** [comment]
I already have fixed this and tested the food for about two months now. I'll submit this to git soon.

**Comment by topas-rec** [comment]
The food: the fix.

**Comment by piem** [comment]
Hi @topas-rec,

thanks for the patch. `aubionotes` already emits midi notes. `aubioonset` could emit a midi signal too. I will do this later today.

For the midiclock, I wrote one using openFrameworks and [ofxAubio](https://github.com/aubio/ofxAubio), i will publish my changes soon.

Best, Paul

**Comment by lukejagger** [comment]
Hi, I know this is an old report, but did you ever implement the MIDI Clock output from aubiotrack?  I only see tap tempo output notes.

**Comment by topas-rec** [comment]
I don't really know what the clock output is.
What I asked here was implemented though.
