### ISSUE TITLE
Issue with PyAudio / SpeechRecognition Integration

### ISSUE THREAD

**Issue by jhoelzl** [aubio/aubio#67]
Hello,

i am using Python 2.7.6 on Ubuntu 14.04 LTS.

I tried to integrate the aubio pitch detection into the  [SpeechRecognition](https://github.com/Uberi/speech_recognition) module: https://github.com/jhoelzl/speech_recognition/commit/355a95297125c3d2546b2b0bb2f4a2ea062d70c2

However, the function `pitch = pitch_o(signal)[0]` (https://github.com/jhoelzl/speech_recognition/commit/355a95297125c3d2546b2b0bb2f4a2ea062d70c2#diff-873076ce119583cd8f8e749e2465a287R484) always returns

`('Unexpected error:', <type 'exceptions.UnboundLocalError'>)`.

Does anybody has an idea or suggestion?

Thanks for support,

Regards,
Josef

**Comment by piem** [comment]
Hi @jhoelzl ,

It seems you are overwriting ``aubio.pitch`` in ``pitch = pitch_o(signal)[0]``. The following patch seems to help: [t.diff.gz](https://github.com/aubio/aubio/files/471760/t.diff.gz).

[SpeechRecognition](https://github.com/Uberi/speech_recognition) looks great. How are you planning to use aubio in it? I would be interested to know more!

Best, Paul

**Comment by jhoelzl** [comment]
Thank you very much @piem , now it works!

I am using the SpeechRecognition module for several months and it is indeed a handy tool.

However, voice activity detector in the SpeechRecognition module has to be improved. Currently, only the overall energy level in the frame is used as a measure (which is not very smart), so i have integrated the WebRTC VAD which measures the energy level in noise and speech band. 

In addition, i also want to measure MFCC (added from [python_speech_features](https://github.com/jameslyons/python_speech_features)) and pitch (added from your aubio module)

**Comment by piem** [comment]
ok, sounds great! Please make sure you check out the [mfcc in aubio](https://github.com/aubio/aubio/blob/master/python/demos/demo_mfcc.py), and let me know how it is going.

For best results, a simple machine learning algorithm could be trained to discriminate speech / non-speech segments using (some of) these features (energy of each bands, mfcc, pitch, ...).

**Comment by jhoelzl** [comment]
Okay, i have also added the calculation for the MFCCs from your module (https://github.com/jhoelzl/speech_recognition/commit/59a87bf27d9a8828f561a68398ae002ea28b476a), but i get this error:

`('Unexpected error:', <type 'exceptions.ValueError'>)`

when performing `spec = p(signal)`.

**Comment by piem** [comment]
strange. when trying your latest git, I get this instead:

```
[...]
Say something!
Traceback (most recent call last):
  File "examples/microphone_recognition.py", line 11, in <module>
    audio = r.listen(source)
  File "/home/piem/projects/aubio/contrib/speech_recognition/speech_recognition/__init__.py", line 490, in listen
    spec = p(signal)
ValueError: input fvec has length 1024, but pvoc expects length 128
```

**Comment by jhoelzl** [comment]
Hi, yes it is working now, when i disable the WebRTC Vad module. The problem is, that the WebRTC VAD requires a frame size of 10, 20 or 30ms. I have 16kHz, so i have to set the variable `source.CHUNK = 480` in my application to have a 30ms frame.

Then i have problems with the fft_size of the MFCC, because it has to be a power of two.

**Comment by jhoelzl** [comment]
Okay, when i set `m_hop_s = 480` (not `m_win_s // 4`) then it works.

**Comment by piem** [comment]
Good! Yes, as long as the window size is a power of 2, it should work.

Note you could recompile aubio to use fftw3, but i'd recommend using power of 2 lengths for speed.

**Comment by jhoelzl** [comment]
I also added the zero-crossing-rate (ZCR):
https://github.com/jhoelzl/speech_recognition/commit/03185a0e53c2f1fb165c390b54d4bd772bb9f0f0
https://github.com/jhoelzl/speech_recognition/commit/908ebb9b72d93b4c50c01b193d7ce192e4689eb4

However, for the ZCR, i always get values smaller than 0.2.
I though this should be a positive integer value since it is defined as the number of times in a sound sample where the amplitude of the sound wave changes sign.

**Comment by piem** [comment]
hi @jhoelzl 

ZRC is a rate, so you need to divide the number of sign changes by the total number of samples. Here is the [doc in aubio](https://github.com/aubio/aubio/blob/master/src/musicutils.h#L105-L110) and the [actual code](https://github.com/aubio/aubio/blob/master/src/mathutils.c#L580-L597).

Note: the [definition on wikipedia](https://en.wikipedia.org/wiki/Zero-crossing_rate) has a -1 normalisation offset and points to a [different implementation](https://en.wikipedia.org/wiki/Zero-crossing_rate#cite_note-2).

hope this helps,
best, Paul

**Comment by jhoelzl** [comment]
@piem thanks now i understand
