### ISSUE TITLE
Delta and Double Delta MFCCs

### ISSUE THREAD

**Issue by jhoelzl** [aubio/aubio#68]
Hello,

would be nice if you could extend the MFCC example script (https://github.com/aubio/aubio/blob/master/python/demos/demo_mfcc.py) to also calculate delta and double-delta coefficients.

Thanks!

**Comment by piem** [comment]
hi @jhoelzl ,

sure! to get the derivative of the mfccs array, you could use ``numpy.diff``:

```python
d_mfccs = np.diff(mfccs, axis = 0)
dd_mfccs = np.diff(d_mfccs, axis = 0)
```

I'll commit an updated version in a short while.

cheers, piem

**Comment by jhoelzl** [comment]
nice, thanks!
