### ISSUE TITLE
pitch detection on 16 bit PCM

### ISSUE THREAD

**Issue by giffy1** [aubio/aubio#69]
The pitch detection sample worked perfectly fine on a .wav file. Now I want to detect pitch on 16-bit PCM audio sent from an Android phone. The data arrives in the Python script as an integer array, but aubio is expecting 32-bit floats. I can put it in the right format, i.e. np.float32(data), which stops the exception but gives me nonsense results. How should I approach this? I've looked for ways to convert the data into .wav format but nothing that doesn't involve file IO.

EDIT: Tried the solution at https://github.com/aubio/aubio/issues/36, but this didn't work.

**Comment by giffy1** [comment]
I got it working - I was not windowing the data correctly.

**Comment by piem** [comment]
hi @giffy1 

great to know you got it working. Some things to check:

 - samples should be normalised to the range [-1; 1]. Dividing by `32768.` should do the trick
 - for multichannel data, samples should be down-mixed to 1 channel: `sum(channels)/number_of_channels`.
 - you can use `array.astype(aubio.float_type)` to make sure the samples are in the correct format

For instance:
```
samples = (numpy.arange(100)/32768.).astype(aubio.float_type)
```

best, Paul
