### ISSUE TITLE
NaN values from Aubio MFCC 

### ISSUE THREAD

**Issue by thomasfillon** [aubio/aubio#70]
Hi Paul !

I got some strange behaviour from Aubio MFCC (installed from your conda channel).
In fact Aubio may not be responsible for this as it only append when Yaafe is installed in the same conda environment (also installed from conda, Yaafe channel).

Without Yaafe (or with Yaafe installed in some other ways) everything seems OK.
But if I run Aubio MFCC in the same environment than Yaafe (installed from Yaafe conda chanel) I can get some Nan or Inf values when the input signal is null.

See [this gist](https://gist.github.com/thomasfillon/785bc2f1b64e96cf029637b960f2b8e7) for an illustration.

Feel free to ask any further detail.
Maybe this issue need to be move to Yaafe ?

**Comment by thomasfillon** [comment]
Also I have noticed that Yaafe some dependencies (also packaged in Yaafe conda channel) are disable in Aubio conda recipe : _fftw_, _libsndfile_
See [meta.yaml from Yaafe conda recipe](https://github.com/Yaafe/Yaafe/blob/master/conda.recipe/meta.yaml)

Build.sh in Aubio conda recipe : 
`python waf configure --prefix=$PREFIX --disable-samplerate --disable-sndfile --disable-avcodec --disable-fftw3 --disable-jack`

But if I installed only those dependencies and not the Yaafe package everything is fine. It just goes wrong with the Yaafe installation.

**Comment by piem** [comment]
hi Thomas,

i'm not sure what's going on here. if you recompile aubio, do you get any warnings? also, can you reproduce this when using aubio's master HEAD?

cheers, piem

**Comment by piem** [comment]
hi @thomasfillon 

any news on this?

cheers, piem

**Comment by piem** [comment]
more info needed, please re-open as needed.

cheers, piem
