### ISSUE TITLE
AttributeError: 'module' object has no attribute 'float_type'

### ISSUE THREAD

**Issue by Brisdo** [aubio/aubio#74]
Using the python interpreter: 

```
> python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import audio
>>> help(aubio.float_type)
```
returns: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'float_type'
```

And running
``` 
python demo_alsa.py
```
returns: 
```
Starting to listen, press Ctrl+C to stop
Traceback (most recent call last):
File "vc.py", line 39, in <module>
     samples = np.fromstring(data, dtype=aubio.float_type)
AttributeError: 'module' object has no attribute 'float_type'
```

Any idea what the issue is?

**Comment by piem** [comment]
Hi @Brisdo ,

What version of aubio are you running? Make sure you have the latest one.

You can install the version 0.4.3 with:

```
pip install http://aubio.org/pub/aubio-0.4.3.tar.bz2
```

Best, Paul

**Comment by Brisdo** [comment]
@piem - thanks!

I was running 0.4.1 - apparently the version I got when I apt-get installed yesterday.

I also had to install nose2 - I don't think the docs mention it.  Now working through getting some of the demos to work...

**Comment by piem** [comment]
you're welcome @Brisdo. 0.4.3 got in  Debian testing a few days ago, so it should be in the next stable versions of Debian and Ubuntu.

cheers, piem

**Comment by piem** [comment]
oh, and nose2 is used in the tests, I added a note about it in `python/README.md`.

thanks, piem
