### ISSUE TITLE
Python module ImportError: Library not loaded (Libav)

### ISSUE THREAD

**Issue by dpren** [aubio/aubio#76]
`python -m pip install aubio`

`python`

`>>> import aubio`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/aubio/__init__.py", line 4, in <module>
    from ._aubio import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/aubio/_aubio.so, 2): Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.56.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/aubio/_aubio.so
  Reason: image not found`

There appears to missing/mis-versioned Libav dependencies when installing from pip.

I have ffmpeg brew installed, which includes libavcodec.57, but not 56.

**Comment by piem** [comment]
hi @dpren ,

What does the output of `ldd /usr/local/lib/python2.7/site-packages/aubio/_aubio.so` looks like?

Do you have libaubio-dev installed on your system?

aubio should compile fine against libav 11.8 or ffmpeg 3.2.

cheers, piem

**Comment by piem** [comment]
It would help to see the output log of the pip command.

You should be able to get it with:

```shell
aubiourl=https://aubio.org/pub/aubio-0.4.3.tar.bz2
( pip --version && pip uninstall aubio -y -v; pip install --user $aubiourl ) 2>&1 | tee aubio.pip.log
```

To install from the git repository instead, change the url to:

```bash
aubiourl=https://github.com/aubio/aubio.git
```

Note: at the moment, you might get the following error:
```
$ pip install --user aubio
Downloading/unpacking aubio
  Could not find a version that satisfies the requirement aubio (from versions: 0.4.3a1, 0.4.3a2)
Cleaning up...
No distributions matching the version for aubio
Storing debug log for failure in /home/piem/.pip/pip.log
```
You can force installing one the alpha versions with `pip install --pre aubio`, but installing directly from the above urls is preferred.

**Comment by dpren** [comment]
The output of: `otool -L /usr/local/lib/python2.7/site-packages/aubio/_aubio.so`

`/usr/local/lib/python2.7/site-packages/aubio/_aubio.so:
	/usr/local/opt/ffmpeg/lib/libavcodec.56.dylib (compatibility version 56.0.0, current version 56.60.100)
	/usr/local/opt/ffmpeg/lib/libavformat.56.dylib (compatibility version 56.0.0, current version 56.40.101)
	/usr/local/opt/ffmpeg/lib/libavutil.54.dylib (compatibility version 54.0.0, current version 54.31.100)
	/usr/local/opt/ffmpeg/lib/libavresample.2.dylib (compatibility version 2.0.0, current version 2.1.0)
	/usr/local/lib/libsndfile.1.dylib (compatibility version 2.0.0, current version 2.25.0)
	/usr/local/opt/libsamplerate/lib/libsamplerate.0.dylib (compatibility version 2.0.0, current version 2.8.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1256.14.0)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 492.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)`


And no, libaubio-dev is not installed.

**Comment by dpren** [comment]
Here's the output of the URL install command:

`pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
Uninstalling aubio-0.4.3a2:
  Removing file or directory /usr/local/bin/aubiocut
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio-0.4.3a2.dist-info/DESCRIPTION.rst
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio-0.4.3a2.dist-info/INSTALLER
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio-0.4.3a2.dist-info/METADATA
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio-0.4.3a2.dist-info/RECORD
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio-0.4.3a2.dist-info/WHEEL
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio-0.4.3a2.dist-info/metadata.json
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio-0.4.3a2.dist-info/top_level.txt
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio/__init__.py
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio/__init__.pyc
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio/_aubio.so
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio/midiconv.py
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio/midiconv.pyc
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio/slicing.py
  Removing file or directory /usr/local/lib/python2.7/site-packages/aubio/slicing.pyc
  Successfully uninstalled aubio-0.4.3a2
Collecting https://aubio.org/pub/aubio-0.4.3.tar.bz2
  Downloading https://aubio.org/pub/aubio-0.4.3.tar.bz2 (328kB)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from aubio===0.4.3-libaubio)
Building wheels for collected packages: aubio
  Running setup.py bdist_wheel for aubio: started
  Running setup.py bdist_wheel for aubio: finished with status 'done'
  Stored in directory: /Users/dperntic/Library/Caches/pip/wheels/9d/6a/b9/d5022253aa25edb2715838d0faced01c6904c3c3e9ef24030c
Successfully built aubio
Installing collected packages: aubio
Successfully installed aubio-0.4.3-libaubio`


Aubio imports just fine now.

**Comment by piem** [comment]
ok. the problem is that pip wants to build a fat binary, for both i386 and x86_64, but brew installs binaries for your platform, either x86_64 or i386, so we must convince pip to no build with both `-arch i386` and `-arch x86_64`.

Not sure what was fixed here, i will upload the source package on pypi...

**Comment by piem** [comment]
Ok, the problem came from a binary on pypi that was compiled with a different ffmpeg. I pushed aubio 0.4.3.post1 (source only) to fix this issue. Quick recap:

To install the **stable** python aubio, use:
```bash
$ pip install aubio
```

To install the **latest** version of python aubio:
```bash
$ pip install git+https://github.com/aubio/aubio.git
```

Thanks for the report, let us know if you run into any other bug.

cheers, piem
