### ISSUE TITLE
Problem building an Xcode project with included aubio.framework

### ISSUE THREAD

**Issue by simonator123** [aubio/aubio#89]
I recently downloaded aubio-0.4.4.framework for iOS from aubio.org. I made a new Xcode (version 8.2.1) project and included the aubio framework; I didn't add any code yet, just the dependency. When attempting to build the project and run it on my attached iPhone (I'm signing the app with my developer certificate), I get the following error: 

App installation failed
Could not inspect the application package

The error I get when running the sample app on iPhone 7 (it builds fine) is "Failed to load info.plist from bundle at path /.../AubioTest2.app/Frameworks/aubio.framework.

I'm more concerned about fixing the iPhone error, cause I like to debug my applications on my iPhone.

**Comment by piem** [comment]
@MartinHN any idea what could be missing here?

@simonator123 apparently the Info.plist was not included in the zip file (it wasn't in earlier versions either). A few questions to find out more:

 - Does it help if you copy [this Info.plist](https://github.com/aubio/aubio/blob/master/scripts/apple/Info.plist) in your local aubio.framework directory?
 - What version of XCode are you using?
 - Did you also add Accelerate.framework?
 - Can you confirm you are using [aubio.framework for iOS](https://aubio.org/bin/0.4.4/aubio-0.4.4.iosuniversal_framework.zip)?
 - Does it run in the simulator?

**Comment by simonator123** [comment]
I added the info.plist you linked me to to the framework you linked me to and I used that one.  Before, the simulator was complaining about the info.plist missing from the framework. Now that that is there, the simulator runs just fine against a short example:

let a = new_fvec(512)
fvec_ones(a)
fvec_print(a)
var method = "default"
let b = new_aubio_tempo(method, 512, 256, 44100)
let c = new_aubio_pitch("default", 512, 256, 32000)
         
aubio_tempo_get_bpm(b)
del_aubio_tempo(b)
del_aubio_pitch(c)
del_fvec(a)"

it still won't run on my connected iPhone. Though, now the error has changed! So, I guess that means we are making progress; or, maybe not cause the error now says, "App installation failed. An unknown error has occurred", pretty generic.

XCode version = 8.2.1
I do have Accelerate.framework included.

Has the framework been tested successfully on Xcode 8.2.1? If so, can I get an example project?

**Comment by simonator123** [comment]
I just saw this in the device log:

_validateSignatureAndCopyInfoForURL:withOptions:error:]: 147: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.UXaCxt/extracted/AubioTest2.app/Frameworks/aubio.framework : 0xe8008001 (An unknown error has occurred.)

**Comment by simonator123** [comment]
I've just done a little bit of research on this, and this is what I've gathered so far. aubio.framework is not signed, and it appears that Xcode is supposed to sign the framework for me with my developer certificate. In looking at the device log, it appears that Xcode is trying to do that, but it is getting stuck on the error I mentioned above. Some stackoverflow posts mention that the info.plist file might be bad. Is it possible that the info.plist file you gave me to put into aubio.framework is bad? Maybe something is missing or some data is not right?

**Comment by piem** [comment]
thanks for the additional info @simonator123. I guess the Info.plist is missing a few keys for the newest Xcode. We are looking at it and will let you know asap. Please also update this issue with any more info you might find on the way.

cheers, piem

**Comment by MartinHN** [comment]
Hi guys,
in the info pist paul gaved, CFBundleSignature field is set to ????
I think it was a default line from old Xcode, in a recent Xcode when creating an blank IOS Framework project, this field is not set anymore
@paul, we may need to add an aubio identifier here , something like  com.aubio.aubioIOSFWK may be?


Martin

**Comment by simonator123** [comment]
Thanks guys for the timely responses. Here is my device output when running the build on my attached iPhone. Also, I tried changing the CFBundleSignature field in info.plist, and the build still failed (I made sure the clean the project and delete derived data as well).

eb 26 09:00:28 Jared-Simons-iPhone streaming_zip_conduit(MobileInstallation)[1758] <Notice>: <private>:InstallApplication:1:Success:<private>
Feb 26 09:00:28 Jared-Simons-iPhone streaming_zip_conduit(MobileInstallation)[1758] <Notice>: <private>:InstallProgress:0:Fail:<private>
Feb 26 09:00:28 Jared-Simons-iPhone installd(MobileSystemServices)[1739] <Notice>: 0x16e01f000 -[MIClientConnection installURL:withOptions:completion:]: Running installation as QOS_CLASS_USER_INITIATED
Feb 26 09:00:28 Jared-Simons-iPhone installd(MobileSystemServices)[1739] <Notice>: 0x16e1c3000 -[MIClientConnection _doInstallationForURL:withOptions:completion:]: Install of "/var/mobile/Media/PublicStaging/AubioTest2.app" type Developer (LSInstallType = (null)) requested by streaming_zip_conduit (pid 1758)
Feb 26 09:00:28 Jared-Simons-iPhone SpringBoard(FrontBoard)[57] <Info>: Added app termination assertion for pid:1739 - <FBApplicationTerminationAssertion: 0x17045e180; serial: 167; reason: critical; bundleID: com.pr.AubioTest2>
Feb 26 09:00:28 Jared-Simons-iPhone installd(MobileSystemServices)[1739] <Notice>: 0x16e1c3000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundle ID=com.pr.AubioTest2; Version=1, ShortVersion=1.0>
Feb 26 09:00:28 Jared-Simons-iPhone installd(MobileInstallation)[1739] <Notice>: <private>:Install (New):0:Success:Begin
Feb 26 09:00:28 Jared-Simons-iPhone misagent(Security)[1754] <Notice>: could not enable test hierarchy: ApplePinningAllowTestCertsiPhoneProvisioningProfileSigning not true
Feb 26 09:00:28 Jared-Simons-iPhone SpringBoard(FrontBoard)[57] <Info>: Reloading provisioning profiles...
Feb 26 09:00:28 Jared-Simons-iPhone SpringBoard(FrontBoard)[57] <Info>: Loaded profiles after 0.00s: {
    "iPhone Developer: Jared Simon (QV7D76576E)" =     (
        "<FBApplicationProvisioningProfile: 0x171054c10; signerIdentity: iPhone Developer: Jared Simon (QV7D76576E); expirationDate: February 11, 2018 at 6:19:37 PM CST>"
    );
}
Feb 26 09:00:28 Jared-Simons-iPhone installd(Security)[1739] <Notice>: could not enable test hierarchy: ApplePinningAllowTestCertsiPhoneApplicationSigning not true
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: SubjectCommonName =(leaf)[]> 0
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: CheckLeafMarkerOid =(leaf)[]> 0
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: IssuerCommonName =(path)[]> 0
Feb 26 09:00:28 Jared-Simons-iPhone installd(Security)[1739] <Notice>:  [leaf CheckLeafMarkerOid IssuerCommonName SubjectCommonName]
Feb 26 09:00:28 Jared-Simons-iPhone installd(Security)[1739] <Notice>: could not enable test hierarchy: ApplePinningAllowTestCertsiPhoneApplicationSigning not true
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: SubjectCommonName =(leaf)[]> 0
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: CheckLeafMarkerOid =(leaf)[]> 0
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: IssuerCommonName =(path)[]> 0
Feb 26 09:00:28 Jared-Simons-iPhone installd(Security)[1739] <Notice>:  [leaf CheckLeafMarkerOid IssuerCommonName SubjectCommonName]
Feb 26 09:00:28 Jared-Simons-iPhone installd(libmis.dylib)[1739] <Info>: cert trust result = 5
Feb 26 09:00:28 Jared-Simons-iPhone profiled[183] <Notice>: Provisioning profiles changed
Feb 26 09:00:28 Jared-Simons-iPhone installd(libmis.dylib)[1739] <Info>: CreateMISAuthListWithStream: open stream failed (may be non-existing)
Feb 26 09:00:28 Jared-Simons-iPhone installd(libmis.dylib)[1739] <Info>: CreateMISAuthListWithStream: creating empty auth list
Feb 26 09:00:28 Jared-Simons-iPhone installd(Security)[1739] <Notice>: could not enable test hierarchy: ApplePinningAllowTestCertsiPhoneProvisioningProfileSigning not true
Feb 26 09:00:28 Jared-Simons-iPhone installd(libmis.dylib)[1739] <Error>: unrecognized status -67049 from codesigning library
Feb 26 09:00:28 Jared-Simons-iPhone installd(libmis.dylib)[1739] <Notice>: Could not copy code signature (error 0xe8008001).
Feb 26 09:00:28 Jared-Simons-iPhone installd(MobileSystemServices)[1739] <Notice>: 0x16e1c3000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 147: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.y1HqbD/extracted/AubioTest2.app/Frameworks/aubio.framework : 0xe8008001 (An unknown error has occurred.)
Feb 26 09:00:28 Jared-Simons-iPhone installd(MobileSystemServices)[1739] <Notice>: 0x16e1c3000 -[MIInstaller performInstallationWithError:]: Verification stage failed
Feb 26 09:00:28 Jared-Simons-iPhone SpringBoard(FrontBoard)[57] <Info>: Removing app termination assertion for pid:1739 - <FBApplicationTerminationAssertion: 0x17045e180; serial: 167; reason: critical; bundleID: com.pr.AubioTest2>
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: NonEmptySubject =(leaf)[]> 0
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: AnchorTrusted =(leaf)[force]> 0
Feb 26 09:00:28 Jared-Simons-iPhone profiled[183] <Notice>: Updating MIS trust...
Feb 26 09:00:28 Jared-Simons-iPhone DuetHeuristic-BM(DuetActivitySchedulerDaemon)[132] <Notice>: Trigger: <private> is now [1]
Feb 26 09:00:28 Jared-Simons-iPhone DuetHeuristic-BM(DuetActivitySchedulerDaemon)[132] <Notice>: Trigger: <private> is now [0]
Feb 26 09:00:28 Jared-Simons-iPhone installd(MobileInstallation)[1739] <Notice>: <private>:Install (New):0:Fail:End
Feb 26 09:00:28 Jared-Simons-iPhone streaming_zip_conduit(MobileInstallation)[1758] <Notice>: <private>:InstallApplication:2:Fail:<private>
Feb 26 09:00:28 Jared-Simons-iPhone streaming_zip_conduit[1758] <Notice>: __dispatch_source_read_socket_block_invoke:312: Failed to install application at file:///var/mobile/Media/PublicStaging/AubioTest2.app/ : Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.y1HqbD/extracted/AubioTest2.app/Frameworks/aubio.framework : 0xe8008001 (An unknown error has occurred.)" UserInfo={LibMISErrorNumber=-402620415, LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=147, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.y1HqbD/extracted/AubioTest2.app/Frameworks/aubio.framework : 0xe8008001 (An unknown error has occurred.)}
Feb 26 09:00:28 Jared-Simons-iPhone SpringBoard(MobileCoreServices)[57] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone SpringBoard(MobileCoreServices)[57] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone SpringBoard(FrontBoard)[57] <Error>: Applications did fail to install: (
    "<LSApplicationProxy: 0x137d56f60> com.pr.AubioTest2 (null) <com.pr.AubioTest2 <INVALID >>"
) (appInfos: (
))
Feb 26 09:00:28 Jared-Simons-iPhone UserEventAgent(MobileCoreServices)[25] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone apsd(MobileCoreServices)[93] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone backupd(MobileCoreServices)[1864] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone BTServer(MobileCoreServices)[64] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone homed(MobileCoreServices)[157] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone nsurlsessiond(MobileCoreServices)[131] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone atc(MobileCoreServices)[38] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone passd(MobileCoreServices)[158] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone routined(MobileCoreServices)[33] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone iaptransportd(MobileCoreServices)[71] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone appstored(MobileCoreServices)[161] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone profiled(MobileCoreServices)[183] <Error>: LaunchServices observer: Apps Failed be installed: <private>
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: NonEmptySubject =(leaf)[]> 0
Feb 26 09:00:28 Jared-Simons-iPhone securityd[106] <Notice>: cert[0]: AnchorTrusted =(leaf)[force]> 0
Feb 26 09:00:28 Jared-Simons-iPhone mobile_installation_proxy(liblockdown.dylib)[1737] <Info>: Checked in with lockdown on path 'xpc' socket 4 without SSL
Feb 26 09:00:28 Jared-Simons-iPhone mobile_installation_proxy(liblockdown.dylib)[1737] <Info>: The connection is now invalid.
Feb 26 09:00:28 Jared-Simons-iPhone mobile_installation_proxy(liblockdown.dylib)[1737] <Info>: Checked in with lockdown on path 'xpc' socket 4 without SSL
Feb 26 09:00:28 Jared-Simons-iPhone mobile_installation_proxy(liblockdown.dylib)[1737] <Info>: The connection is now invalid.
Feb 26 09:00:28 Jared-Simons-iPhone UserEventAgent(PersistentConnection)[25] <Notice>: 2017-02-26 09:00:28 -0600 UserEventAgent[25] BTA-com.apple.timed: Invalidating simple timer <PCSimpleTimer: 0x1033464a0>
Feb 26 09:00:28 Jared-Simons-iPhone UserEventAgent(PersistentConnection)[25] <Notice>: 2017-02-26 09:00:28 -0600 UserEventAgent[25]: <PCDispatchTimer: 0x10031c2d0> is invalidated 
Callstack (
	0   PersistentConnection                0x00000001890305cc <redacted> + 116
	1   PersistentConnection                0x000000018902dfb8 <redacted> + 292
	2   com.apple.BackgroundTaskAgentPlugin 0x000000010078bb34 com.apple.BackgroundTaskAgentPlugin + 15156
	3   com.apple.BackgroundTaskAgentPlugin 0x000000010078ad8c com.apple.BackgroundTaskAgentPlugin + 11660
	4   com.apple.BackgroundTaskAgentPlugin 0x000000010078a978 com.apple.BackgroundTaskAgentPlugin + 10616
	5   libdispatch.dylib                   0x00000001850e21bc <redacted> + 16
	6   libdispatch.dylib                   0x00000001850eef94 <redacted> + 576
	7   libdispatch.dylib                   0x00000001850fb634 <redacted> + 204
	8   libdispatch.dylib                   0x00000001850e4160 <redacted> + 820
	9   libdispatch.dylib                   0x00000001850f0210 <redacted> + 468
	10  libdispatch.dylib                   0x00000001850e59a4 <redacte
Feb 26 09:00:28 Jared-Simons-iPhone UserEventAgent(PersistentConnection)[25] <Notice>: 2017-02-26 09:00:28 -0600 UserEventAgent[25]: <PCDispatchTimer: 0x10031c2d0> dealloced
Feb 26 09:00:28 Jared-Simons-iPhone UserEventAgent(PersistentConnection)[25] <Notice>: 2017-02-26 09:00:28 -0600 UserEventAgent[25]: <PCDispatchTimer: 0x100349b50> is invalidated 
Callstack (
	0   PersistentConnection                0x00000001890305cc <redacted> + 116
	1   PersistentConnection                0x000000018902dfd4 <redacted> + 320
	2   com.apple.BackgroundTaskAgentPlugin 0x000000010078bb34 com.apple.BackgroundTaskAgentPlugin + 15156
	3   com.apple.BackgroundTaskAgentPlugin 0x000000010078ad8c com.apple.BackgroundTaskAgentPlugin + 11660
	4   com.apple.BackgroundTaskAgentPlugin 0x000000010078a978 com.apple.BackgroundTaskAgentPlugin + 10616
	5   libdispatch.dylib                   0x00000001850e21bc <redacted> + 16
	6   libdispatch.dylib                   0x00000001850eef94 <redacted> + 576
	7   libdispatch.dylib                   0x00000001850fb634 <redacted> + 204
	8   libdispatch.dylib                   0x00000001850e4160 <redacted> + 820
	9   libdispatch.dylib                   0x00000001850f0210 <redacted> + 468
	10  libdispatch.dylib                   0x00000001850e59a4 <redacte

**Comment by piem** [comment]
hello @simonator123 

i just tried creating a simple swift application using Xcode 8.2.1, adding the framework provided at https://aubio.org/download (no Info.plist) using drag-n-drop, and everything runs fine on my device!

how did you add aubio.framework to your project?

cheers, piem

**Comment by piem** [comment]
Here is a tiny example showing how to read samples from a file:

```swift
let path = Bundle.main.path(forResource: "example", ofType: "mp4")
if (path != nil) {
    let hop_size : uint_t = 512
    let a = new_fvec(hop_size)
    let b = new_aubio_source(path, 0, hop_size)
    var read: uint_t = 0
    var total_frames : uint_t = 0
    while (true) {
        aubio_source_do(b, a, &read)
        total_frames += read
        if (read < hop_size) { break }
    }
    print("read", total_frames, "frames at", aubio_source_get_samplerate(b), "Hz")
    del_aubio_source(b)
    del_fvec(a)
} else {
    print("could not find file")
}
```

**Comment by simonator123** [comment]
Eureeka!!! It worked! I tried your drag-n-drop method and then inspected the general page. I noticed that the framework was only included in the Linked Frameworks and Binaries section, and not in the Embedded Binaries. I had been adding the framework to the Embedded Binaries section (which adds the framework to both sections). The reason I was doing that is because that had worked for other frameworks I have used, and I was also doing it that way because when you add an embedded binary it brings up by default a list of frameworks in your Xcode project and the Linked Frameworks section does not by default; you have to click "Add Other", so it just made sense in my mind to use the other method. 

Why do other frameworks work for me when you add them to the Embedded Binaries section? 

Why isn't the info.plist file needed for aubio.framework? 

I added the small example to the project and when I built it on my device, I got the below errors. 

Undefined symbols for architecture arm64:
  "_ExtAudioFileSeek", referenced from:
      _aubio_source_apple_audio_seek in aubio(source_apple_audio.c.1.o)
  "_ExtAudioFileRead", referenced from:
      _aubio_source_apple_audio_do in aubio(source_apple_audio.c.1.o)
      _aubio_source_apple_audio_do_multi in aubio(source_apple_audio.c.1.o)
  "_ExtAudioFileDispose", referenced from:
      _aubio_source_apple_audio_close in aubio(source_apple_audio.c.1.o)
      _del_aubio_source_apple_audio in aubio(source_apple_audio.c.1.o)
  "_ExtAudioFileOpenURL", referenced from:
      _aubio_source_apple_audio_open in aubio(source_apple_audio.c.1.o)
  "_ExtAudioFileGetProperty", referenced from:
      _aubio_source_apple_audio_open in aubio(source_apple_audio.c.1.o)
      _aubio_source_apple_audio_seek in aubio(source_apple_audio.c.1.o)
      _aubio_source_apple_audio_get_duration in aubio(source_apple_audio.c.1.o)
  "_ExtAudioFileSetProperty", referenced from:
      _aubio_source_apple_audio_open in aubio(source_apple_audio.c.1.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by simonator123** [comment]
Why the way, sorry for all the trouble! I'm new to Xcode and still trying to figure out how some of these things work!

**Comment by piem** [comment]
Great to know it works @simonator123 !

_Why do other frameworks work for me when you add them to the Embedded Binaries section?_

Because they are dynamically built, whereas aubio.framework is built statically. Until quite recently, it was not possible to link dynamically on iOS, so we built aubio.framework statically.

_Why isn't the info.plist file needed for aubio.framework?_

Apparently, it's not!

_Why is the build failing with `undefined symbols to ExtAudioFileRead`?_
 
For the example provided, you will need to add the AudioToolbox framework as well.

**Comment by piem** [comment]
@simonator123 I updated the [documentation](https://aubio.readthedocs.io/en/latest/xcode_frameworks.html) to include the small example above. I didn't change the instructions to add aubio to an existing project. Let us know if you think of something that could improve them!

**Comment by simonator123** [comment]
My apologies. The proper instructions were already in the documentation. I should have read them at the start. 

Thanks for your help.

**Comment by simonator123** [comment]
Fantastic onset documentation. Thank you.

What would you say is the best way to send real-time iPhone mic data to aubio to get onset timings? It appears from the onset example that I have to find a way to get a sequence of floating point numbers coming from the iPhone mic and use that to put data into a pointer to a fvec_t struct to send to aubio_onset_do. Correct? What would you say is the best way to do this? I noticed that aubio has jackio, but I'm doubtful that will let me record input from the iPhone. 

In doing some research, I have come across references to iOS audio queues, AVAudioRecorder, AudioUnit, and AVCaptureAudioDataOutput. I found an example that I think I can use:

https://gist.github.com/hotpaw2/ba815fc23b5d642705f2b1dedfaf0107

My thoughts are that I would use what this guy wrote. I would get the necessary data to put into the fvect struct from the 'inputDataList' parameter from the 'processMicrophoneBuffer' buffer.

What do you think? Is there an example you can point me to of what I am trying to do?

**Comment by piem** [comment]
thank you @simonator123,

could you open a new issue for this? your last message will do great a start, for instance with a title like _accessing the mic on iOS_?

i will close this one now, see you on the other side!

piem
