### ISSUE TITLE
Cannot get aubio to compile

### ISSUE THREAD

**Issue by rbohr** [aubio/aubio#93]
Hello

I just installed the aubio library, and I wrote a short C test program to try to get things to initially work, but I cannot compile. Here is the context of my script: I am getting a signal from a USB microphone and putting it into an array of samples, using portaudio library. Next I would like to get this samples array into a fvec_t, so I can use aubio methods to do analysis on the signal, such as onset detection, note classification, tempo detection, etc. I have cloned aubio from git, and did all the instructions on the README.md (I am on a Linux machine using Ubuntu). I did the following commands to install aubio

```
make getwaf
./waf configure
./waf build
sudo ./waf install
```

It seems to install successfully. Now I have #include <aubio/aubio.h> at the top of my C script, but when I try to make a fvec_t with the following line

`fvec_t* ptr = new_fvec(44100)`

And I get the following compile error message

```
/tmp/cc1Av3yx.o: In function `main':
record_aubio.c:(.text+0x7a5): undefined reference to `new_fvec'
collect2: error: ld returned 1 exit status
```

So it seems its not finding the fvec methods, or any of the other aubio methods, but I am including <aubio/aubio.h>, and it seems to find that header file successfully. Assuming I have everything installed right, isn't that the only header I need to include to use aubio library? Maybe I am missing something, please let me know. The end goal is to be able to take an input signal (of a user whistling, or humming), and parse the signal to return the notes that were whistled, as well as what type of note it was (quarter note, eighth note, etc). Thanks very much for your time reading this.

**Comment by piem** [comment]
hi @rbohr 

what command did you use to compile your code? looking at the error message, it seems to be a linker issue. did you add `-laubio`?

You can use `pkg-config` to get the right flags:

    # check which version is installed
    pkg-config --modversion aubio

    # compiling
    gcc `pkg-config --cflags aubio` -c myprog.c -o myprog.o

    # linking
    gcc `pkg-config --libs aubio` myprog.o -o myprog

let us know if that helps,
thanks, piem

**Comment by rbohr** [comment]
Haha adding `-laubio' fixed it. I knew it was something small, thanks very much!
