### ISSUE TITLE
Missing def file for cross compiled DLL

### ISSUE THREAD

**Issue by 7heW4yne** [aubio/aubio#97]
Hello,

I downloaded the cross compiled version of aubio 0.4.4 and tried to write an own small test program on my Windows machine. 

On Windows you can easily create an Import Library for the provided DLL using:
`lib /DEF:libaubio.def`
But I didn't find any DEF file in the download package. Using only a Windows machine, it is a little bit tricky to extract the exports from the DLL and create the DEF file, because the ".a" and ".dll.a" files are useless if you only have Windows.

Perhaps you can enhance your MinGW build script in order to provide also the DEF file for the DLL.
On MinGW it is very easy to create the needed DEF file:
`dlltool -d somedll.def -l libsomedll.a`
For more information please refer to: [HOWTO Create an Import Library for a DLL using MinGW](http://www.mingw.org/wiki/createimportlibraries)

Greetz, Joerg

P.S. For all who need to create the DEF file on a Windows machine. Following script cost about 1 hour of my lifetime, but may helps another poor guy without linux ;-)

> echo EXPORTS > libaubio.def
for /f "usebackq tokens=4 " %%r in (`dumpbin /exports ".\bin\libaubio-5.dll"`) do (
  echo %%r | find /i "_" > nul
  if not errorlevel 1 (echo.  %%r >> libaubio.def)
)

**Comment by piem** [comment]
hi @7heW4yne 

thanks for the script, that's really helpful!

aubio is cross-compiled with  [`scripts/build_mingw`](https://github.com/aubio/aubio/blob/master/scripts/build_mingw) using [mingw64](http://mingw-w64.org/). i wonder if we could get the same results using the mingw64 toolchain on linux.

could you post the `libaubio.def` you generated here?

also why did you use `dumpbin` and not `dlltool`?

thanks, piem

**Comment by 7heW4yne** [comment]
hi piem

on Windows there is no dlltool. That's why I use dumpbin.

Yes, of course. Here is the [zipped libaubio.def](https://github.com/aubio/aubio/files/904753/libaubio.zip) (Github does not support DEF files).
But I recommend to create the def file while cross compiling, to avoid missing to update changed, added or removed function names in the def file.

Maybe you can add the dlltool command to your build_mingw before [line 82](https://github.com/aubio/aubio/blob/master/scripts/build_mingw#L82) ... I am not an expert.

Hth, Joerg

**Comment by piem** [comment]
ok, thanks for the file. a few questions:

 - mingw wiki examples start with `LIBRARY LIBAUBIO.dll`. isn't that required?
 - your example has leading spaces, are they required too?

thanks, piem

**Comment by piem** [comment]
i could generate a libaubio.def using this one liner:

    ( echo -e "LIBAUBIO-5.dll\nEXPORTS"; nm aubio-0.4.5~alpha-win32/lib/libaubio-5.dll | grep T\ _ | egrep "(aubio|fvec|cvec|lvec|fmat)" | cut -d _ -f 2- ) > libaubio-5.def

here is the result: [libaubio-5.def.zip](https://github.com/aubio/aubio/files/905127/libaubio-5.def.zip)

how should the file be named: `libaubio-5.def` or `libaubio.def`?

**Comment by 7heW4yne** [comment]
The `LIBRARY` statement is not required.
The [MSDN Article](https://msdn.microsoft.com/en-us/library/28d6s79h(v=vs.80).aspx) doesn't mention the leading spaces. But all DEF files I've seen, have leading spaces or tabulators. Must be for this stupid ape-like race called "Humans" ;)

Using your def file Visual Studio prints a warning:

> libaubio.def(1) : warning LNK4017: LIBAUBIO-5.dll statement not supported for the target platform; ignored

It's almost perfect. But you missed the `LIBRARY` keyword in front of the dll name.
The first line needs to be `LIBRARY LIBAUBIO-5.dll` or `EXPORTS`.

hth, Joerg

**Comment by piem** [comment]
ok, great! if it's not required, we can just skip that first line.

what about the filename? should it be `libaubio-5.def` or `libaubio.def`?

**Comment by 7heW4yne** [comment]
It doesn't matter. If the Windows user doesn't specify another output filename, the lib gets the same as the def file.
But to have all filenames the same it should be libaubio-5.def.

**Comment by piem** [comment]
@7heW4yne could you try the following binaries:

https://aubio.org/bin/tmp/aubio-0.4.5~git+d609841+mods-win32.zip
https://aubio.org/bin/tmp/aubio-0.4.5~git+d609841+mods-win64.zip

also, it would be great if you could check these ones, built against the [latest ffmpeg windows build](https://ffmpeg.zeranoe.com/), `20170404-1229007`.

https://aubio.org/bin/tmp/aubio-0.4.5~git+d609841+mods-win32-ffmpeg.zip
https://aubio.org/bin/tmp/aubio-0.4.5~git+d609841+mods-win64-ffmpeg.zip

**Comment by piem** [comment]
hi @7heW4yne 

i've just pushed the updated script to generate .def files at build time, closing this issue.
please re-open if you find any issue with them.

thanks for your report,
piem
